function WC = wave_colors(obj) %#ok<INUSD>

WC = struct('cpoke_timer',   [1   0 0  ], 'wait_wave', [0 1 0]);

%       'stim_wave',          [1   1   1  ],     ...
%       'rew_wave',           [1   1   1  ],     ...
%       'rew_big_wave',       [1   1   1  ],     ...
%       'noseincenter_wave',  [1   1   1  ],     ...
%       'endNIC_wave',        [1   1   1  ],     ...
%       'legalcbreak_wave',   [1   1   1  ],     ...
%       'miniLCB_wave',       [1   1   1  ],     ...
%       'prestim_wave',       [1   1   1  ],     ...
%       'memoryzap_wave',     [1   1   1  ],     ...
%       'bad_nic_wave',       [1   1   1  ],     ...
%       'stimulator_wave',    [1   1   0  ],     ...
%       'stimulator_wave1',   [1   1   0  ],     ...
%       'stimulator_wave2',   [1   1   0  ],     ...
%       'stimulator_wave3',   [1   1   0  ],     ...
%       'stimulator_wave4',   [1   1   0  ],     ...
      