function Specs = specify_pericommitment_analyses
% specifications for peri-commitment analyses
Specs = struct;
Specs.linewidth = 1;
Specs.EIthreshold = 1/3;
Specs.plots = ["pref_minus_null"; ...
    "pref_minus_null_CM"; ...
    "pref_minus_null_EA"; ...
    "rightleft_fit_PC1"; ...
    "rightleft_fit_PC2"; ...
    "rightleft_fit_PC3"; ...
    "rightleft_notfit_PC1"; ...
    "rightleft_notfit_PC2"; ...
    "rightleft_notfit_PC3"; ...
    ];
