function max_state_dur = MaxStateDur(obj) %#ok<INUSD>


max_state_dur = {...
'state_0',                  120;...
'check_next_trial_ready',   120;...
'wait_for_cin',             Inf;...
'context',                  120;...
'nicstim',                  120;...
'stimon_nosein',            120;...
'stimon_noseout',           120;...
'reinit_cpoke',              60;...
'start_new_trial',           60;...
'wait_for_cout',            120;...
'csgap',                     60;...
'free_choice',              Inf;...
'left_reward',               60;...
'right_reward',              60;...
'post_freechoice_wait',      60;...
'stim_on',                  Inf;...
'stim_off',                  60;...
'wait_for_spoke',           Inf;...
'son_reward_chooser',       120;...
'soff_reward_chooser',      120;...
'reward_big_soff',          120;...
'reward_big_son',           120;...
'reward_big_soffwon',       120;...
'reward_soff',              120;...
'reward_son',               120;...
'reward_soffwon',           120;...
'post_reward_on',           120;...
'post_reward_off',          120;...
'soft_drink_time',          120;...
'warndanger',               120;...
'warndanger_warning',       120;...
'warndanger_danger',        120;...
'error_state',              120;...
'temperror',                120;...
'start_new_trial',           30;...
'final_state',               30;...
};