function SC = state_colors(obj) %#ok<INUSD>
SC=struct(...
'iti_state_long', 				colors('corn silk'),...
'iti_state_short',				colors('light yellow'),...
'nic_precue_stereo',			colors('white smoke'),...
'nic_precue_left',				colors('sky blue'),...
'nic_precue_right',				colors('light salmon'),...
'nic_precue_high',				colors('violet'),...
'nic_cue',					colors('purple'),...
'nic_postcue',				colors('violet'),...
'wait_for_nopoke',				colors('khaki'),...
'wait_for_cpoke',				colors('gold'),...
'hit_state',					colors('teal'),...
'miss_state',					colors('light coral'),...
'left_reward_state',			colors('light green'),...
'right_reward_state',			colors('pale green'),...
'timeout_state',				colors('crimson'),...
'violation_state',				colors('crimson'),...
'pre_clean_up_state',			colors('silver'));