function wcolors = wave_colors(obj)

wcolors = struct(...
      'stim_wave',          [1   1   1  ],     ...
      'rew_wave',           [1   1   1  ],     ...
      'rew_big_wave',       [1   1   1  ],     ...
      'noseincenter_wave',  [1   1   1  ],     ...
      'legalcbreak_wave',   [1   1   1  ],     ...
      'prestim_wave',       [1   1   1  ],     ...
      'memoryzap_wave',     [1   1   1  ],     ...
      'bad_nic_wave',       [1   1   1  ]);

end