function WC = wave_colors(obj) %#ok<INUSD>

WC = struct(...
      'bad_nic_wave',       [1   1   1  ], ...
      'stimulator_wave',    [1   1   0  ], ...
      'stimulator_wave1',   [1   1   0  ], ...
      'stimulator_wave2',   [1   1   0  ], ...
      'stimulator_wave3',   [1   1   0  ], ...
      'stimulator_wave4',   [1   1   0  ], ...
      'stimulator_wave5',   [1   1   0  ], ...
      'var_gap1_wave',      [1   1   1  ], ...
      'var_gap2_wave',      [1   1   1  ], ...
      'noseincenter_wave',  [1   1   1  ], ...
      'legalcbreak_wave',   [1   1   1  ]);