function max_state_dur = MaxStateDur(obj) %#ok<INUSD>

max_state_dur = {...
    'state_0',                  120;...
    'check_next_trial_ready',   120;...
    'wait_for_cpoke',           Inf;...
    'settling_in',               30;...
    'cpoke',                     30;...
    'wait_for_sounds_to_end',    30;...
    'early_spoke_state',         30;...
    'give_reward',               30;...
    'go_sound_state',            30;...
    'give_reward',               30;...
    'wait_for_spoke',           Inf;...
    'hit_state',                 30;...
    'drink_state',               60;...
    'temp_error_state',          60;...
    'wait_for_spoke_retry',     Inf;...
    'retry_hit_state',           60;...
    'error_state',              120;...
    'violation_state',          120;...
    'general_final_state',      120;...
    'hit_final_state',          120;...
    'error_final_state',        120;...
    'violation_final_state',    120;...
};

end