function  [varargout] =  SMASection(obj, action)


GetSoloFunctionArgs(obj);


switch action
  
  %% prepare_next_trial
  case 'prepare_next_trial',    
     
     sma = StateMachineAssembler('full_trial_structure', 'use_happenings', 1);
    
     min_time= 1E-4;  % This is close to the minumum time allowed for a state transition.
    
     left1led           = bSettings('get', 'DIOLINES', 'left1led');
     center1led         = bSettings('get', 'DIOLINES', 'center1led');
     right1led          = bSettings('get', 'DIOLINES', 'right1led');
     left1water         = bSettings('get', 'DIOLINES', 'left1water');
     right1water        = bSettings('get', 'DIOLINES', 'right1water');
     
     [sma, plus_pre_nic, minus_pre_nic] = make_perinic_stimulus_scheduled_wave(sma, 'pre_nic_stimulus', ...
        prenic_stim, flash_frequency, center1led, left1led, right1led);
     [sma, plus_nic,     minus_nic]     = make_perinic_stimulus_scheduled_wave(sma, 'nic_stimulus', ...
        nic_stim,    flash_frequency, center1led, left1led, right1led);

     sma = add_scheduled_wave(sma, 'name', 'reward_delay', 'preamble', rw_delay);
     % cpoke timer and associated happening 
     sma = add_scheduled_wave(sma, 'name', 'cpoke_timer', 'preamble', nic, 'sustain', 1e4);
     sma = add_happening_spec(sma, struct(...
        'name',                 {'cpoke_timer_hi',                  'cpoke_timer_lo'}, ...
        'detectorFunctionName', {'wave_high',                           'wave_low'}, ...
        'inputNumber',          {get_wavenumber(sma, 'cpoke_timer'), get_wavenumber(sma, 'cpoke_timer')}));
    
     switch side_lights,
        case 'pro'
           sma = add_scheduled_wave(sma, 'name', 'left_light',   'preamble', lights_delay, ...
              'sustain', 1e4, 'DOut', left1led);
           sma = add_scheduled_wave(sma, 'name', 'right_light',  'preamble', lights_delay, ...
              'sustain', 1e4, 'DOut', right1led);
        case 'anti'
           sma = add_scheduled_wave(sma, 'name', 'left_light',   'preamble', lights_delay, ...
              'sustain', 1e4, 'DOut', right1led);
           sma = add_scheduled_wave(sma, 'name', 'right_light',  'preamble', lights_delay, ...
              'sustain', 1e4, 'DOut', left1led);
        case 'none'
           sma = add_scheduled_wave(sma, 'name', 'left_light',   'preamble', lights_delay);
           sma = add_scheduled_wave(sma, 'name', 'right_light',  'preamble', lights_delay);
        
        otherwise
           error('Sorry, don''t know how to handle side_lights="%s"\n', side_lights);
     end;
     
     % A string to turn ALL waves off, so we collect everything in here.
     all_waves_off = [minus_pre_nic minus_nic ' - reward_delay - left_light - right_light - cpoke_timer'];  
     all_waves_but_side_lights_off = [minus_pre_nic minus_nic ' - reward_delay - cpoke_timer'];

     % Get the sound ids for all the target 1 and 2 sounds, store them in
     % variable of the form class_%d_target1 and class_%d_target2
     for t=1:nClasses,        
        eval(['class_' num2str(t) '_target1 = ' ...
           'SoundManagerSection(obj, ''get_sound_id'', ''ClicksTableSnd' ...
           num2str(eval(['class_' num2str(t) '_target1'])) ''');']);
       
        eval(['class_' num2str(t) '_target2 = ' ...
           'SoundManagerSection(obj, ''get_sound_id'', ''ClicksTableSnd' ...
           num2str(eval(['class_' num2str(t) '_target2'])) ''');']);
     end;
     
     % Make scheduled waves that play the sounds for each of the trial
     % classes. The waves will have names of the form tc%d_t1on and
     % tc%d_t1_off. "tc" stands for "trial class" and t1on and t1off are
     % target1 on and target1 off, respectively.   
     for t=1:nClasses,
        sma = add_scheduled_wave(sma, 'name', sprintf('tc%d_t1on', t), ...
           'preamble', t1_on_delay, 'sustain', 100, ...
           'sound_trig',  eval(['class_' num2str(t) '_target1']));
        sma = add_scheduled_wave(sma, 'name', sprintf('tc%d_t1off', t), ...
           'preamble', t1_off_delay, ...
           'untrigger_on_down',  sprintf('tc%d_t1on', t));
       
        sma = add_scheduled_wave(sma, 'name', sprintf('tc%d_t2on', t), ...
           'preamble', t2_on_delay, 'sustain', 100, ...
           'sound_trig',  eval(['class_' num2str(t) '_target2']));
        sma = add_scheduled_wave(sma, 'name', sprintf('tc%d_t2off', t), ...
           'preamble', t2_off_delay, ...
           'untrigger_on_down',  sprintf('tc%d_t2on', t));
        
        all_waves_off                 = [sprintf(' - tc%d_t1on - tc%d_t1off - tc%d_t2on - tc%d_t2off', t, t, t, t) all_waves_off]; %#ok<AGROW>
        all_waves_but_side_lights_off = [sprintf(' - tc%d_t1on - tc%d_t1off - tc%d_t2on - tc%d_t2off', t, t, t, t) ...
           all_waves_but_side_lights_off]; %#ok<AGROW>
     end;

     % Define the correct and incorrect responses for each trial class:
     left_response = cell(nClasses, 1); right_response = cell(nClasses, 1);
     for t=1:nClasses,
        myside = eval(sprintf('class_%d_side', t));
        if myside=='l',
           left_response{t}  = sprintf('left_hit_%d', t);
           if temp_v_error==1, right_response{t} = 'error_state';
           else                right_response{t} = 'right_temp_error';
           end;
        else
           right_response{t} = sprintf('right_hit_%d', t);
           if temp_v_error==1, left_response{t}  = 'error_state';
           else                left_response{t}  = 'left_temp_error';
           end;
        end;
     end;
     
     % Finally, we make a scheduled wave that acts as a flag that a
     % cviolation occurred:
     sma = add_scheduled_wave(sma, 'name', 'cviolation_flag', 'preamble', 0, ...
        'sustain', 1e4, 'refraction', 0);
     sma = add_happening_spec(sma, struct(...
        'name',                 {'cviolation_flag_hi',                  'cviolation_flag_lo'}, ...
        'detectorFunctionName', {'wave_high',                           'wave_low'}, ...
        'inputNumber',          {get_wavenumber(sma, 'cviolation_flag'), get_wavenumber(sma, 'cviolation_flag')}));

     
     
     sma = add_state(sma, 'name', 'wait_for_cpoke', ...
           'output_actions', {'SchedWaveTrig', plus_pre_nic}, ...
           'input_to_statechange', {'Cin', 'cpoke'});

     
     % Ok, now add the probabilistic jump based on the prob_vector we are
     % given:
     cpkss = cell(1, nClasses);
     posterior_probs = zeros(1, nClasses);
     for t=1:nClasses,
        cpkss{t} = sprintf('cpoke%d', t);
        posterior_probs(t) = TrialsSection(obj, 'get', t, 'posterior');
     end;
     
     sma = add_state(sma, 'name', 'cpoke', 'self_timer', 1e-4, ...
        'input_to_statechange', {'Tup', 'main_distributor'});
     sma = add_probabilistic_jump(sma, 'main_distributor', posterior_probs, cpkss);     
     
     % Now we add a cpoke and wait_for_cpoke_out and
     % wait_for_spoke state for each of the trial classes:
     
     for t=1:nClasses,
     
        % Now define which scheduled waves will be triggered at various
        % points. Different waves play the different stimuli for different
        % trial classes.
        
        % First, the ones common to all trial classes: (we also want to
        % always DEtrigger pre_nic_stimulus on Cin, and DEtrigger
        % nic_stimulus on end of nic, but because we can't mix + and - triggering
        % of scheduled waves in a single state, we'll do those separately.
        waves_to_trigger_on_Cin =  [plus_nic ' + cpoke_timer'];  % on cpoke in
        waves_to_trigger_on_Sin = ' + reward_delay';  % on side poke in
        if eval(['class_' num2str(t) '_side'])=='r',
           waves_to_trigger_on_Cout = '+ right_light';                % on cpoke out
        else
           waves_to_trigger_on_Cout = '+ left_light';                 % on cpoke out
        end;
        
        % Now the ones for this particular trial type, anchored at the
        % appropriate points:
        
        for possible_anchors = {'Cin' 'Cout' 'Sin'},
           anchor = possible_anchors{1};
           if strcmp(t1_on_anchor, anchor)
              newwaves = [sprintf(' + tc%d_t1on', t) eval(['waves_to_trigger_on_' anchor])]; %#ok<NASGU>
              eval(['waves_to_trigger_on_' anchor ' = newwaves;']);
           end;
           if strcmp(t1_off_anchor, anchor)
              newwaves = [sprintf(' + tc%d_t1off', t) eval(['waves_to_trigger_on_' anchor])]; %#ok<NASGU>
              eval(['waves_to_trigger_on_' anchor ' = newwaves;']);
           end;
           
           if strcmp(t2_on_anchor, anchor)
              newwaves = [sprintf(' + tc%d_t2on', t) eval(['waves_to_trigger_on_' anchor])]; %#ok<NASGU>
              eval(['waves_to_trigger_on_' anchor ' = newwaves;']);
           end;
           if strcmp(t2_off_anchor, anchor)
              newwaves = [sprintf(' + tc%d_t2off', t) eval(['waves_to_trigger_on_' anchor])]; %#ok<NASGU>
              eval(['waves_to_trigger_on_' anchor ' = newwaves;']);
           end;
        end;
        
     
        % Now the cpoke state itself:
        
        % stop pre-nic waves
        sma = add_state(sma, 'name', sprintf('cpoke%d', t), 'self_timer', min_time, ...
           'output_actions', {'SchedWaveTrig', minus_pre_nic}, ...
           'input_to_statechange', {'Tup', 'current_state+1'});

        % nic init waves
        sma = add_state(sma, 'self_timer', min_time, ...
           'output_actions', {'SchedWaveTrig', waves_to_trigger_on_Cin}, ...
           'input_to_statechange', {...
           'Tup', 'current_state+1', ...
           'Clo', 'cviolation', ...
           'Lhi', 'sviolation', ...
           'Rhi', 'sviolation'});
       
        % min time for nic post-entry duration
        sma = add_state(sma, 'self_timer', nic_mintime, ...
            'input_to_statechange',  {...
            'Tup', 'current_state+1', ...
            'Cout', 'cviolation', ...
            'Lhi', 'sviolation', ...
            'Rhi', 'sviolation'});
        
        % passed nic_mintime: check cpoke timer state 
        sma = add_state(sma, 'self_timer', 1e6, ...
            'input_to_statechange',  {...
            'cpoke_timer_hi', sprintf('wait_for_cout%d', t), ...
            'Cout', 'current_state+1', ...
            'Lhi', 'sviolation', ...
            'Rhi', 'sviolation'});
        
        % legal_cbreak
        % Note: for now, a side poke during legal_cbreak goes to sviolation
        sma = add_state(sma, 'self_timer', legal_cbreak, ...
            'input_to_statechange',  {...
            'Cin', 'current_state-2', ...
            'Tup', 'cviolation', ...
            'Lhi', 'sviolation', ...
            'Rhi', 'sviolation'});
            
        
        % And wait_for_cout:
        sma = add_state(sma, 'name', sprintf('wait_for_cout%d', t), ...
           'self_timer', 1e6, ...
           'output_actions', {'SchedWaveTrig', minus_nic}, ...
           'input_to_statechange', {...
           'Clo', sprintf('wait_for_spoke%d', t), ...
           'Lhi', 'sviolation', ...
           'Rhi', 'sviolation'});
     
        % And wait_for_spoke:
        sma = add_state(sma, 'name', sprintf('wait_for_spoke%d', t), ...
           'self_timer', 1e6, ...
           'output_actions', {'SchedWaveTrig', waves_to_trigger_on_Cout}, ...
           'input_to_statechange', { ...
           'Lin', left_response{t}, ...
           'Rin', right_response{t}});                
     end;
     
     % cviolation plays the cviolation sound then goes back to main
     % distributor again.
     sma = add_state(sma, 'name', 'cviolation', ...
        'self_timer', cviol_dur, ...
        'output_actions', {...
        'SchedWaveTrig', all_waves_off, ...
        'SoundOut', SoundManagerSection(obj, 'get_sound_id', 'cviolation_sound')}, ...
        'input_to_statechange', {'Tup', 'current_state+1'});
     if reinit_cpoke==false,
        % If C is hi at the end of the c violation, that suffices to
        % restart the cpoke state:
        sma = add_state(sma, 'self_timer', 1e-4, ...
           'output_actions', {'SchedWaveTrig', 'cviolation_flag'}, ...
           'input_to_statechange', {'Chi', 'cpoke' ; ...
           'Tup', 'wait_for_cpoke'});
     else
        % we always go to a wait_for_cpoke state, wherein an actual Cin
        % event will be required to restart cpoke; Chi is not enough.
        sma = add_state(sma, 'self_timer', 1e-4, ...
           'output_actions', {'SchedWaveTrig', 'cviolation_flag'}, ...
           'input_to_statechange', {'Tup', 'wait_for_cpoke'});
     end;
     
     % sviolation currently does the same as cviolation, with a Cin requirement.
     sma = add_state(sma, 'name', 'sviolation', ...
        'self_timer', cviol_dur, ...
        'output_actions', {...
        'SchedWaveTrig', all_waves_off, ...
        'SoundOut', SoundManagerSection(obj, 'get_sound_id', 'cviolation_sound')}, ...
        'input_to_statechange', {'Tup', 'wait_for_cpoke'});
     
     
     errorpun_id = SoundManagerSection(obj, 'get_sound_id', 'errorpun');
     sma = add_state(sma, 'name', 'error_state', ...
        'self_timer', errorpun_dur, ...
        'output_actions', {'SchedWaveTrig', all_waves_off, ...
        'SoundOut', errorpun_id}, ...
        'input_to_statechange', {'Tup', 'current_state+1'});
     sma = add_state(sma, 'self_timer', min_time, ...
        'output_actions', {'SoundOut', -errorpun_id}, ...
        'input_to_statechange', {'Tup', 'check_next_trial_ready'});
     
     
     [LeftWValveTime, RightWValveTime] = WaterValvesSection(obj, 'get_water_times');

     % Add the left response and right hit states:
     for t=1:nClasses,
        % LEFT:
        % trigger and wait for the reward delay to be over:
        sma = add_state(sma, 'name', sprintf('left_hit_%d', t), ...
           'output_actions', {'SchedWaveTrig', waves_to_trigger_on_Sin}, ...
           'input_to_statechange', {'reward_delay_In', sprintf('left_water_%d', t)});
        % go to either regular water, or small if there was a cviolation:
        sma = add_state(sma, 'name', sprintf('left_water_%d', t), ...
           'input_to_statechange', {'cviolation_flag_hi', sprintf('small_left_water_%d', t), ...
                                    'cviolation_flag_lo', 'current_state+1'});
        % good water time:
        sma = add_state(sma, ...                                 
           'self_timer', CGoodWaterFactor*LeftWValveTime*eval(sprintf('class_%d_wtr_mul', t)), ...
           'output_actions', {'DOut', left1water}, ...           
           'input_to_statechange', {'Tup', 'left_drink_time'});
        % violation water time:
        sma = add_state(sma, 'name', sprintf('small_left_water_%d', t), ...                                 
           'self_timer', CViolWaterFactor*LeftWValveTime*eval(sprintf('class_%d_wtr_mul', t)), ...
           'output_actions', {'DOut', left1water}, ...           
           'input_to_statechange', {'Tup', 'left_drink_time'});

        % RIGHT:
        % trigger and wait for the reward delay to be over:
        sma = add_state(sma, 'name', sprintf('right_hit_%d', t), ...
           'output_actions', {'SchedWaveTrig', waves_to_trigger_on_Sin}, ...
           'input_to_statechange', {'reward_delay_In', sprintf('right_water_%d', t)});
        % go to either regular water, or small if there was a cviolation:
        sma = add_state(sma, 'name', sprintf('right_water_%d', t), ...
           'input_to_statechange', {'cviolation_flag_hi', sprintf('small_right_water_%d', t), ...
                                    'cviolation_flag_lo', 'current_state+1'});
        % good water time:
        sma = add_state(sma, ...                                 
           'self_timer', CGoodWaterFactor*RightWValveTime*eval(sprintf('class_%d_wtr_mul', t)), ...
           'output_actions', {'DOut', right1water}, ...           
           'input_to_statechange', {'Tup', 'right_drink_time'});
        % violation water time:
        sma = add_state(sma, 'name', sprintf('small_right_water_%d', t), ...                                 
           'self_timer', CViolWaterFactor*RightWValveTime*eval(sprintf('class_%d_wtr_mul', t)), ...
           'output_actions', {'DOut', right1water}, ...           
           'input_to_statechange', {'Tup', 'right_drink_time'});               
     end;
     
     % If we poked in the left but that was a temp error:
     temppun_id = SoundManagerSection(obj, 'get_sound_id', 'temppun');
     sma = add_state(sma, 'name', 'left_temp_error', ...
        'self_timer', temppun_dur, ...
        'output_actions', {'SchedWaveTrig', all_waves_but_side_lights_off, ...
        'SoundOut', temppun_id}, ...
        'input_to_statechange', {'Tup', 'current_state+1'});
     % after the left temp error, punish again if poke on left and reward is available in the right:
     sma = add_state(sma,  ... 
        'output_actions', {'SoundOut', -temppun_id}, ...
        'input_to_statechange', {'Lin', 'current_state-1', ...
        'Rin', 'current_state+1'});
     % but reward is available only after a delay:
     sma = add_state(sma, ... 
        'output_actions', {'SchedWaveTrig', 'reward_delay'}, ...
        'input_to_statechange', {'reward_delay_In', 'current_state+1'});     
     % reward size depends on whether there was a cviolation:
     sma = add_state(sma, ...
        'input_to_statechange', {'cviolation_flag_hi', 'small_right_water_0', ...
                                 'cviolation_flag_lo', 'right_water_0'});
     % And the reward state itself:
     sma = add_state(sma, 'name', 'right_water_0', ...
        'self_timer', CGoodWaterFactor*RightWValveTime, ...
        'output_actions', {'DOut', right1water}, ...
        'input_to_statechange', {'Tup', 'right_drink_time'});
     sma = add_state(sma, 'name', 'small_right_water_0', ...
        'self_timer', CViolWaterFactor*RightWValveTime, ...
        'output_actions', {'DOut', right1water}, ...
        'input_to_statechange', {'Tup', 'right_drink_time'});
     
     
     % If we poked in the right but that was a temp error:
     temppun_id = SoundManagerSection(obj, 'get_sound_id', 'temppun');
     sma = add_state(sma, 'name', 'right_temp_error', ...
        'self_timer', temppun_dur, ...
        'output_actions', {'SchedWaveTrig', all_waves_but_side_lights_off, ...
        'SoundOut', temppun_id}, ...
        'input_to_statechange', {'Tup', 'current_state+1'});
     % after the right temp error, punish again if poke on right and reward is available in the left:
     sma = add_state(sma, ... 
        'output_actions', {'SoundOut', -temppun_id}, ...
        'input_to_statechange', {'Rin', 'current_state-1', ...
        'Lin', 'current_state+1'});
     % but reward is available only after a delay:
     sma = add_state(sma, ... 
        'output_actions', {'SchedWaveTrig', 'reward_delay'}, ...
        'input_to_statechange', {'reward_delay_In', 'current_state+1'});
     % reward size depends on whether there was a cviolation:
     sma = add_state(sma, ...
        'input_to_statechange', {'cviolation_flag_hi', 'small_left_water_0', ...
                                 'cviolation_flag_lo', 'left_water_0'});
     % And the reward state itself:
     sma = add_state(sma, 'name', 'left_water_0', ...
        'self_timer', CGoodWaterFactor*LeftWValveTime, ...
        'output_actions', {'DOut', left1water}, ...
        'input_to_statechange', {'Tup', 'left_drink_time'});
     sma = add_state(sma, 'name', 'small_left_water_0', ...
        'self_timer', CViolWaterFactor*LeftWValveTime, ...
        'output_actions', {'DOut', left1water}, ...
        'input_to_statechange', {'Tup', 'left_drink_time'});
     

     sma = add_scheduled_wave(sma, 'name', 'soft_drink_cap', 'preamble', SoftDrinkCap);

     sma = add_state(sma, 'name', 'left_drink_time', 'self_timer', min_time, ...
        'output_actions', {'SchedWaveTrig', all_waves_off}, ...
        'input_to_statechange', {'Tup', 'current_state+1'});
     sma = add_state(sma, 'output_actions', {'SchedWaveTrig', 'soft_drink_cap'}, ...
        'input_to_statechange', {...
        'Llo', 'current_state+2', ...
        'Lhi', 'current_state+1'});
     sma = add_state(sma, ...
        'input_to_statechange', {...
        'soft_drink_cap_In', 'warning', ...
        'Llo',               'current_state+1'});
     sma = add_state(sma, 'self_timer', SoftDrinkGrace, ...
        'input_to_statechange', {...
        'Tup',               'warning', ...
        'soft_drink_cap_In', 'warning', ...
        'Lhi',               'current_state-1'});
     
     sma = add_state(sma, 'name', 'right_drink_time', 'self_timer', min_time, ...
        'output_actions', {'SchedWaveTrig', all_waves_off}, ...
        'input_to_statechange', {'Tup', 'current_state+1'});
     sma = add_state(sma, 'output_actions', {'SchedWaveTrig', 'soft_drink_cap'}, ...
        'input_to_statechange', {...
        'Rlo', 'current_state+2', ...
        'Rhi', 'current_state+1'});
     sma = add_state(sma, ...
        'input_to_statechange', {...
        'soft_drink_cap_In', 'warning', ...
        'Rlo',               'current_state+1'});
     sma = add_state(sma, 'self_timer', SoftDrinkGrace, ...
        'input_to_statechange', {...
        'Tup',               'warning', ...
        'soft_drink_cap_In', 'warning', ...
        'Rhi',               'current_state-1'});
     
     warning_sound_id = SoundManagerSection(obj, 'get_sound_id', 'warning_sound');
        
     sma = add_state(sma, 'name', 'warning', ...
        'self_timer', SoundManagerSection(obj, 'get_sound_duration', 'warning_sound'), ...
        'output_actions', {'SoundOut', warning_sound_id}, ...
        'input_to_statechange', {'Tup', 'current_state+1'});
     sma = add_state(sma, 'self_timer', min_time, ...
        'output_actions', {'SoundOut', -warning_sound_id}, ...
        'input_to_statechange', {'Tup', 'check_next_trial_ready'});
     
     
     % collect all names of prepare_next_trial states:
     
     prepare_next_trial_states = cell(nClasses, 2);
     for t=1:nClasses,
        prepare_next_trial_states{t,1} = sprintf('left_hit_%d',    t);
        prepare_next_trial_states{t,2} = sprintf('right_hit_%d',   t);
     end;
     prepare_next_trial_states = prepare_next_trial_states(:);
     prepare_next_trial_states{end+1} = 'left_temp_error';
     prepare_next_trial_states{end+1} = 'right_temp_error';
     prepare_next_trial_states{end+1} = 'error_state';
     dispatcher('send_assembler', sma, prepare_next_trial_states');

   %% case state_colors
   case 'state_colors'
      varargout{1} = struct( ...
          'wait_for_cpoke',       [220 115 215]/255, ...  % orchid
          'cpoke',                [0.52 0.76 1], ...
          'main_distributor',     [1    1    1], ...      % white
          'cpoke1',               [0.52 0.76 1], ...
          'cpoke2',               [0.52 0.72 1], ...
          'cpoke3',               [0.52 0.68 1], ...
          'cpoke4',               [0.52 0.64 1], ...
          'wait_for_cout1',       [0.52 0.64 1]*0.6, ...
          'wait_for_cout2',       [0.52 0.64 1]*0.6, ...
          'wait_for_cout3',       [0.52 0.64 1]*0.6, ...
          'wait_for_cout4',       [0.52 0.64 1]*0.6, ...
          'cviolation',          [1   0.45 0.45], ...
          'sviolation',          [1   0.45 0.45], ...
          'wait_for_spoke1',     [132 111 255]/255, ...  % slate blue
          'wait_for_spoke2',     [132 106 240]/255, ...  % slate blue
          'wait_for_spoke3',     [132 101 225]/255, ...  % slate blue
          'wait_for_spoke4',     [132  96 210]/255, ...  % slate blue
          'left_temp_error',     [0.4 0.2 0.2]/255, ...
          'right_temp_error',    [0.4 0.2 0.2]/255, ...
          'left_hit_1',          [50  255  50]/355, ...  % green
          'left_hit_2',          [50  255  50]/355, ...  % green
          'left_hit_3',          [50  255  50]/355, ...  % green
          'left_hit_4',          [50  255  50]/355, ...  % green
          'right_hit_1',         [50  255  50]/355, ...  % green
          'right_hit_2',         [50  255  50]/355, ...  % green
          'right_hit_3',         [50  255  50]/355, ...  % green
          'right_hit_4',         [50  255  50]/355, ...  % green
          'right_water_0',       [50  255  50]/255, ...  % green
          'right_water_1',       [50  255  50]/255, ...  % green
          'right_water_2',       [50  255  50]/255, ...  % green
          'right_water_3',       [50  255  50]/255, ...  % green
          'right_water_4',       [50  255  50]/255, ...  % green
          'right_drink_time',    [50  255  50]/255, ...  % green
          'left_water_0',        [50  255  50]/255, ...  % green
          'left_water_1',        [50  255  50]/255, ...  % green
          'left_water_2',        [50  255  50]/255, ...  % green
          'left_water_3',        [50  255  50]/255, ...  % green
          'left_water_4',        [50  255  50]/255, ...  % green
          'left_drink_time',     [50  255  50]/255, ...  % green
          'warning',             [0.3  0    0],    ...   % dark maroon
          'error_state',         [255   0   0]/255, ...  % red
          'state_0',             [1   1   1  ],  ...
          'iti',                 [0.5 0.5 0.5], ...
          'check_next_trial_ready',     [0.7 0.7 0.7]);

       
   %% case wave_colors
   case 'wave_colors'
      varargout{1} = struct( ...
         'cviolation_flag',     [1 1 0]);
      
end;






%% function make_perinic_stimulus_scheduled_wave

function [sma, plus_name, minus_name] = make_perinic_stimulus_scheduled_wave(sma, name, stim_type, ...
   flash_frequency, center1led, left1led, right1led)
     % Make a scheduled wave that will control the perinic stimuli
     switch stim_type
        case 'C LED on',
           sma = add_scheduled_wave(sma, 'name', name, ...
              'preamble', 0, 'sustain', 10, 'refraction', 0, 'loop', -1, ...
              'DOut', center1led);
           plus_name  = ['+' name];
           minus_name = ['-' name];
        case 'C LED flash',
           sma = add_scheduled_wave(sma, 'name', name, ...
              'preamble', 0, 'sustain', 0.5/flash_frequency, 'refraction', 0.5/flash_frequency, ...
              'loop', -1, 'DOut', center1led);
           plus_name  = ['+' name];
           minus_name = ['-' name];
        case 'C/S LEDs counterflash'
           sma = add_scheduled_wave(sma, 'name', [name '_1'], ...
              'preamble', 0.5/flash_frequency, 'sustain', 0.5/flash_frequency, 'refraction', 0, ...
              'loop', -1, 'DOut', center1led);
           sma = add_scheduled_wave(sma, 'name', [name '_2'], ...
              'preamble', 0, 'sustain', 0.5/flash_frequency, 'refraction', 0.5/flash_frequency, ...
              'loop', -1, 'DOut', left1led);
           sma = add_scheduled_wave(sma, 'name', [name '_3'], ...
              'preamble', 0, 'sustain', 0.5/flash_frequency, 'refraction', 0.5/flash_frequency, ...
              'loop', -1, 'DOut', right1led);           
           plus_name   = sprintf('+ %s_1 + %s_2 + %s_3', name, name, name);
           minus_name  = sprintf('- %s_1 - %s_2 - %s_3', name, name, name);
        case 'sound', 
           error('sound not yet implemented for %s', name);
           % sma = add_scheduled_wave(sma, 'name', 'prenic_stimulus', ...
           %   'preamble', 0, 'sustain', value(prenic_sound_dur), 'refraction', 0, 'loop', -1, ...
           %   'sound_trig', SoundManagerSection(obj, 'get_sound_id', 'prenic_sound'));
        case 'none',
           sma = add_scheduled_wave(sma, 'name', name, ...
              'preamble', 0, 'sustain', 0, 'refraction', 0);
           plus_name  = ['+' name];
           minus_name = ['-' name];
        otherwise
           error('Sorry, don''t recognize %s = "%s"\n', name, stim_type);
     end;

     return;
     