function room_turnover_indicator

disp('Room Turnover Indicator Update...');
pname = pwd;
cd('C:\ratter\ExperPort\')

tw = 5; %time window in minutes
ne = 4; %number of events within time window

try
        t = now;
        wg = bdata(['select timeval from ratinfo.mass where date="',datestr(now,'yyyy-mm-dd'),...
            '" and timeval>"',datestr(now-(tw/(24*60)),'HH:MM:SS'),'"']);

        [et,hn] = bdata(['select endtime, hostname from sessions where sessiondate="',datestr(now,'yyyy-mm-dd'),...
            '" and endtime>"',datestr(now-(tw/(24*60)),'HH:MM:SS'),'"']);
        bad=[];
        for i=1:numel(hn)
            if numel(hn{i})<4 || isempty(str2num(hn{i}(4:end))) || str2num(hn{i}(4:end))>38
                bad(end+1)=i; 
            end
        end
        et(bad)=[];

        st = bdata(['select starttime from sess_started where sessiondate="',datestr(now,'yyyy-mm-dd'),...
            '" and starttime>"',datestr(now-(tw/(24*60)),'HH:MM:SS'),'" and rigid<39']);

        events = numel(wg) + numel(et) + numel(st);
        
        if events ==0
            %room not being turned over
            try %#ok<TRYNC>
                system('blink1-tool --green');
            end

        elseif events < ne
            %some activity in room
            try %#ok<TRYNC>
                system('blink1-tool --rgb=255,190,0');
            end

        else
            %turnover happening
            try %#ok<TRYNC>
                system('blink1-tool --red');
            end
        end
        
catch
    %error, white so we know it's not just a power issue
    system('blink1-tool --rgb=255,255,255');      
end

cd(pname);


%     x = [1,   0,   0;...
%          1,   0.2, 0;...
%          1,   0.4, 0;...
%          1,   0.6, 0;...
%          1,   0.8, 0;...
%          1,   1,   0;...
%          0.8, 1,   0;...
%          0.6, 1,   0;...
%          0.4, 1,   0;...
%          0.2, 1,   0;...
%          0,   1,   0;...
%          0,   1,   0.2;...
%          0,   1,   0.4;...
%          0,   1,   0.6;...
%          0,   1,   0.8;...
%          0,   1,   1;...
%          0,   0.8, 1;...
%          0,   0.6, 1;...
%          0,   0.4, 1;...
%          0,   0.2, 1;...
%          0,   0,   1;...
%          0.2, 0,   1;...
%          0.4, 0,   1;...
%          0.6, 0,   1;...
%          0.8, 0,   1;...
%          1,   0,   1;...
%          1,   0,   0.8;...
%          1,   0,   0.6;...
%          1,   0,   0.4;...
%          1,   0,   0.2]; 
%     z = sum(x,2);
%     for i=1:3
%         x(:,i) = x(:,i) ./ z;
%     end
%      
%     x = round(x * 255);
%     while 1
%         for i = 1:size(x,1)
%             try
%                 system(['blink1-tool --rgb=',num2str(x(i,1)),',',num2str(x(i,2)),',',num2str(x(i,3))]);
%             end
%             pause(0.1);
%         end
%     end