function WC = wave_colors(obj) %#ok<INUSD>

WC = struct(...
      'stim_wave',          [1   1   1  ],     ...
      'rew_wave',           [1   1   1  ],     ...
      'rew_big_wave',       [1   1   1  ],     ...
      'noseincenter_wave',  [1   1   1  ],     ...
      'endNIC_wave',        [1   1   1  ],     ...
      'legalcbreak_wave',   [1   1   1  ],     ...
      'miniLCB_wave',       [1   1   1  ],     ...
      'prestim_wave',       [1   1   1  ],     ...
      'memoryzap_wave',     [1   1   1  ],     ...
      'bad_nic_wave',       [1   1   1  ],     ...
      'stimulator_wave',    [1   1   1  ],     ...
      'stimulator_wave1',   [1   1   1  ],     ...
      'stimulator_wave2',   [1   1   1  ],     ...
      'stimulator_wave3',   [1   1   1  ],     ...
      'stimulator_wave4',   [1   1   1  ],     ...
      'stimulator_wave5',   [1   1   1  ]);