function SC = state_colors(obj) %#ok<INUSD>
SC=struct(...
'iti_state_long', 				colors('corn silk'),...
'iti_state_short',				colors('light yellow'),...
'nic_precue_stereo',			colors('white smoke'),...
'nic_cue_stereo',				colors('gray'),...
'nic_postcue_stereo',			colors('white smoke'),...
'nic_precue_left',				colors('sky blue'),...
'nic_cue_left',					colors('royal blue'),...
'nic_postcue_left',				colors('sky blue'),...
'nic_precue_right',				colors('light salmon'),...
'nic_cue_right',				colors('orange red'),...
'nic_postcue_right',			colors('light salmon'),...
'nic_precue_high',				colors('violet'),...
'nic_cue_high',					colors('purple'),...
'nic_postcue_high',				colors('violet'),...
'flash1_left',					colors('steel blue'),...
'gap_left',						colors('thistle'),...
'flash2_left',					colors('steel blue'),...
'flash1_right',					colors('coral'),...
'gap_right',					colors('thistle'),...
'flash2_right',					colors('coral'),...
'flash1_both',					colors('slate gray'),...
'gap_both',						colors('thistle'),...
'flash2_both',					colors('slate gray'),...
'flash1_none',					colors('old lace'),...
'gap_none',						colors('old lace'),...
'flash2_none',					colors('old lace'),...
'wait_for_nopoke',				colors('khaki'),...
'wait_for_cpoke',				colors('gold'),...
'nogo_state',					colors('olive'),...
'hit_state',					colors('teal'),...
'correct_rejection_state',		colors('cyan'),...
'miss_state',					colors('light coral'),...
'left_reward_state',			colors('light green'),...
'right_reward_state',			colors('pale green'),...
'center_reward_state',			colors('lime green'),... 
'false_alarm_state',			colors('tomato'),...
'timeout_state',				colors('crimson'),...
'violation_state',				colors('crimson'),...
'pre_clean_up_state',			colors('silver'));