function SC = state_colors(obj) %#ok<INUSD>

% Colors that the various states take when plotting
% can i label the states differently?
SC = struct( ...
    'delay2start',                       [.6   .6  .6],...
    'wait_for_poke1',                    [1    .8  .8],...
    'poke1sound',                        [1    .7  .4],...
    'wait_for_poke2',                    [1    .9  .6],... 
	'poke2leds',                         [.9   .9  .9],...
    'poke2sound',                        [.7   1   .7],...
    'wait_for_poke3',                    [.6  .66   1],...
    'wait_for_poke3_aftertemperror', 0.7*[.6  .66   1],...
	'soft_drink_time',                   [.66 .98 .57],...
	'soft_drink_time_aftertemperror',0.7*[.66 .98 .57],...
    'hit_iti',                           [.35  1   .3],...
    'miss_iti',                          [1    0  .17],...
    'violation_iti',                     [.5  .01 .01],...
    'wd_warning',                        [0.3  0    0],...
    'wd_danger',                         [0.5 .05 .05] ...
    );


