function checktrainproblems3(day,varargin)

try
    if nargin < 1; day = now; end

    [TR,TG,TS,TE,TI,TN] = bdata(['select ratname, rigid, timeslot, experimenter, techinitials,',...
                        ' note from ratinfo.technotes where datestr="',datestr(day,'yyyy-mm-dd'),'"']);
    [CE,CM,CI] = bdata('select experimenter, email, initials from ratinfo.contacts where is_alumni=0');
    [RR,RC] = bdata('select ratname, contact from ratinfo.rats');
    [SR,SS,SG] = bdata(['select ratname, timeslot, rig from ratinfo.schedule where date="',datestr(day,'yyyy-mm-dd'),'"']);

    set_email_sender;

    OWNERS = cell(1,numel(TN));

    for i = 1:numel(TR)
        if ~isempty(TR{i})
            x = find(strcmp(RR,TR{i})==1,1,'first');
            if ~isempty(x)
                contact = RC{x}; 
                owners = get_owners(contact);
                OWNERS{i}(end+1:end+numel(owners)) = owners;
            end
        end
    end

    for i = 1:numel(TG)
        if ~isnan(TG(i))
            ratnames = SR(SG == TG(i));
            ratnames(strcmp(ratnames,'')) = [];

            for j = 1:numel(ratnames)
                x = find(strcmp(RR,ratnames{j})==1,1,'first');
                if ~isempty(x)
                    contact = RC{x}; 
                    owners = get_owners(contact);
                    OWNERS{i}(end+1:end+numel(owners)) = owners;
                end
            end
        end
    end

    for i = 1:numel(TS)
        if ~isnan(TS(i))
            ratnames = SR(SS == TS(i));
            ratnames(strcmp(ratnames,'')) = [];

            for j = 1:numel(ratnames)
                x = find(strcmp(RR,ratnames{j})==1,1,'first');
                if ~isempty(x)
                    contact = RC{x}; 
                    owners = get_owners(contact);
                    OWNERS{i}(end+1:end+numel(owners)) = owners;
                end
            end
        end
    end

    for i = 1:numel(TE)
        if ~isempty(TE{i})
            x = find(strcmpi(CE,TE{i})==1,1,'first');
            if ~isempty(x)
                contact = CM{x};
                contact(find(contact=='@',1,'first'):end) = [];
                OWNERS{i} = {contact};
            end
        end
    end

    for i = 1:numel(OWNERS)
        OWNERS{i} = unique(OWNERS{i});
    end

    NOTES = cell(1,numel(TN));
    %NOTES = cell(0);
    for i = 1:numel(TN)
        if     ~isempty(TR{i}); note = TR{i};
        elseif ~isnan(TG(i));   note = ['Rig ',num2str(TG(i))];
        elseif ~isnan(TS(i));   note = ['Session ',num2str(TS(i))];
        elseif ~isempty(TE{i}); note = TE{i};
        else,                   note = 'General';
        end
        if ~isempty(strfind(char(TN{i}'),'confirmed empty')) ||... %#ok<STREMP>
            ~isempty(strfind(char(TN{i}'),'Watering ended in Pub')) %#ok<STREMP>
            %This is the tech confirming a room was empty or that the pub
            %was ended. Do not email this note to everyone
            OWNERS{i} = ' ';
            continue;
        end

        x = find(strcmpi(CI,TI{i})==1,1,'first');
        if ~isempty(x)
            author = CE{x};
        else
            author = 'unknown';
        end

        note = [note,' TechNote by ',author,': ',char(TN{i}')]; %#ok<AGROW>

        NOTES{i} = note;
    end

    contact = cell(1,numel(CM));
    for i = 1:numel(CM)
        contact{i} = CM{i}(1:find(CM{i}=='@',1,'first')-1);
    end

    for i = 1:numel(OWNERS)
        if isempty(OWNERS{i})
            OWNERS{i} = contact;
        end
    end

    for i = 1:numel(contact)
        message = cell(0);
        message{1} = [CE{i},','];
        message{2} = 'Below are all TechNotes relevant for your rats yesterday.';
        message{3} = ' ';

        for j = 1:numel(OWNERS)
            x = sum(strcmp(OWNERS{j},contact{i}));
            if x > 0
                message{end+1} = NOTES{j}; %#ok<AGROW>
                message{end+1} = ' '; %#ok<AGROW>
            end
        end

        if numel(message) > 3
            IP = get_network_info;
            if ischar(IP); message{end+1} = ['Email generated by ',IP]; %#ok<AGROW>
            else,          message{end+1} =  'Email generated by an unknown computer!!!'; %#ok<AGROW>
            end

            message{end+1} = 'ratter\ExperPort\Utility\AutomatedEmails\checktrainproblems3.m'; %#ok<AGROW>

            disp(message');

            sendmail(CM{i},'Potential Training Problems',message)
            %sendmail('ckopec@princeton.edu','Potential Training Problems',message)
        end
    end
catch
    senderror_report;
end




function owners = get_owners(contact)

bks = find(contact == ' ' | contact == ',' | contact == ';' | contact == ':');
bks = [0 bks numel(contact)+1];

owners = cell(0);
for i = 1:numel(bks)-1
    temp = contact(bks(i)+1:bks(i+1)-1);
    if ~isempty(temp)
        owners{end+1} = temp; %#ok<AGROW>
    end
end