function email_tech_schedule(DT)

try
    dt1 = DT{1};
    dt2 = DT{2};

    %setpref('Internet','SMTP_Server','brodyfs2.princeton.edu');
    %setpref('Internet','E_mail',['TechSchedule',datestr(now,'yymm'),'@Princeton.EDU']);
    set_email_sender
    
    [A,B,C,D,Y] = bdata(['select overnight, morning, evening, date, day from ratinfo.tech_schedule where date>="',dt1,'" and date<="',dt2,'"']); %#ok<NASGU>
    [E,Z] = bdata('select experimenter, email from ratinfo.contacts where is_alumni=0');

    for i = 1:numel(E)
        eval(['M.',E{i},'={};']);
    end

    for i = 1:numel(D)

        m = find(A{i} == '[');
        n = find(A{i} == ']');
        if ~isempty(m) && ~isempty(n) && m < n
            A{i}(m:n) = []; 
        end

        temp = A{i};
        brks = find(temp==' ' | temp==',' | temp==';');
        brks = [0,brks,numel(temp)+1];
        names = cell(0);
        for b = 1:numel(brks)-1
            temp_name = temp(brks(b)+1:brks(b+1)-1);
            if ~isempty(temp_name)
                names{end+1} = temp_name;
            end
        end
        A{i} = names;
        
        m = find(B{i} == '[');
        n = find(B{i} == ']');
        if ~isempty(m) && ~isempty(n) && m < n
            B{i}(m:n) = []; 
        end

        temp = B{i};
        brks = find(temp==' ' | temp==',' | temp==';');
        brks = [0,brks,numel(temp)+1];
        names = cell(0);
        for b = 1:numel(brks)-1
            temp_name = temp(brks(b)+1:brks(b+1)-1);
            if ~isempty(temp_name)
                names{end+1} = temp_name;
            end
        end
        B{i} = names;
        
        m = find(C{i} == '[');
        n = find(C{i} == ']');
        if ~isempty(m) && ~isempty(n) && m < n
            C{i}(m:n) = []; 
        end
        
        temp = C{i};
        brks = find(temp==' ' | temp==',' | temp==';');
        brks = [0,brks,numel(temp)+1];
        names = cell(0);
        for b = 1:numel(brks)-1
            temp_name = temp(brks(b)+1:brks(b+1)-1);
            if ~isempty(temp_name)
                names{end+1} = temp_name;
            end
        end
        C{i} = names;
        
        for j = 1:numel(E)
            a = []; b = []; c = [];
            
            for k = 1:numel(A{i})
                if strcmp(A{i}{k},E{j}); a = 1; end
            end
            for k = 1:numel(B{i})
                if strcmp(B{i}{k},E{j}); b = 1; end
            end
            for k = 1:numel(C{i})
                if strcmp(C{i}{k},E{j}); c = 1; end
            end
           
            if ~isempty(a) || ~isempty(b) || ~isempty(c)
                eval(['M.',E{j},'{end+1,1} = [D{i},'' '',Y{i}];']);
                eval(['M.',E{j},'{end,1}(end+1:27) = '' '';'])
            end

            if ~isempty(a)
                eval(['M.',E{j},'{end}(23) = ''A'';']);
            end
            if ~isempty(b)
                eval(['M.',E{j},'{end}(25) = ''B'';']);
            end
            if ~isempty(c)
                eval(['M.',E{j},'{end}(27) = ''C'';']);
            end
        end
    end

    for i = 1:numel(E)
        x = eval(['M.',E{i},';']);

        if ~isempty(x)
            x{end+1,1} = ' ';
            x{end+1,1} = E{i};
            x{end+1,1} = ' '; %#ok<*AGROW>
            x{end+1,1} = 'Above are your assigned shifts for the next pay period.';
            x{end+1,1} = 'Please forward this email to Jovanna as confirmation ';
            x{end+1,1} = 'within the next 24 hours.';
            x{end+1,1} = ' ';
            x{end+1,1} = 'Thanks,';
            x{end+1,1} = 'The Tech Schedule Meister';

            IP = get_network_info;
            x{end+1,1} = ' '; 
            if ischar(IP); x{end+1,1} = ['Email generated by ',IP]; 
            else           x{end+1,1} =  'Email generated by unknown computer!!!'; 
            end
            x{end+1,1} = 'ratter\ExperPort\Utility\AutomatedEmails\email_tech_schedule.m';    

            sendmail(Z{i},'Tech Schedule',x)
            sendmail('ckopec@princeton.edu','Tech Schedule',x)
        end
    end
catch
    senderror_report
end
    
       