function  [varargout] =  SMASection(obj, action)


GetSoloFunctionArgs(obj);


switch action
    
    
    case 'prepare_next_trial',
        %% prepare_next_trial
        sma = StateMachineAssembler('full_trial_structure', 'use_happenings', 1);
        
        min_time= 1E-4;  % This is close to the minumum time allowed for a state transition.
        
        left1led           = bSettings('get', 'DIOLINES', 'left1led');
        center1led         = bSettings('get', 'DIOLINES', 'center1led');
        right1led          = bSettings('get', 'DIOLINES', 'right1led');
        left1water         = bSettings('get', 'DIOLINES', 'left1water');
        right1water        = bSettings('get', 'DIOLINES', 'right1water');
        
        target = TrialSection(obj, 'get_target');
        context = TrialSection(obj, 'get_context');
        
        %% set up reward quantity and timing
        hit_streak = 3; % TODO: what's this?
        [LeftWValveTime RightWValveTime] = WaterValvesSection(obj, 'get_water_times', hit_streak);
        
        
        warning_sound   = SoundManagerSection(obj, 'get_sound_id', 'WarningSound');
        danger_sound = SoundManagerSection(obj, 'get_sound_id', 'DangerSound');
        
        % TODO Solo parameters
        % TODO start with short fixations
        % TODO blocks
        
        cviolation_time = 0.05;
        stayout_time = 0.5;
        
        cfix_time = TimeVarsSection(obj, 'get_cfix_time');
        delay_time = TimeVarsSection(obj, 'get_delay_time');
        penalty_time = TimeVarsSection(obj, 'get_penalty_time');
        drinking_time = TimeVarsSection(obj, 'get_drinking_time');
        cbreak_penalty_time = TimeVarsSection(obj, 'get_cbreak_penalty_time');
        forgiveness_delay = TimeVarsSection(obj, 'get_forgiveness_delay');
        
%         fprintf('cfix_time = %.2f\n', value(cfix_time));
        
        if(target == 'l')
            wrong_side = 'r';
            target1water = left1water;
            water_delivery_time = LeftWValveTime;
        else
            wrong_side = 'l';
            target1water = right1water;
            water_delivery_time = RightWValveTime;
        end
        
        if(xor(target == 'l', context == 'a'))
            que_side = 'l';
            que_sound = SoundManagerSection(obj, 'get_sound_id', 'LeftClicks');
        else
            que_side = 'r';
            que_sound = SoundManagerSection(obj, 'get_sound_id', 'RightClicks');
        end
        
        if(context == 'a')
            cfix_statename = 'cfix_anti';
            cfix_lights = center1led;
        else
            cfix_statename = 'cfix_pro';
            cfix_lights = left1led+right1led;
        end
            
        
        sma = add_scheduled_wave(sma, 'name', 'cfix_timer', 'preamble', cfix_time);
        sma = add_scheduled_wave(sma, 'name', 'forgiveness_timer', 'preamble', forgiveness_delay);
        
        max_danger_sound_duration = 5;
        warning_sound_duration = SoundInterface(obj, 'get', 'WarningSound', 'Dur1');
        
        %% clean up sounds
        snd_list=SoundManagerSection(obj, 'get_sound_id','all');
        sma = add_multi_sounds_state(sma, -1*snd_list,'state_name','begin_trial','return_state','wait_for_cpoke');
        % TODO make a sound to signal trial start
        sma = add_state(sma, 'name', 'wait_for_cpoke', ...
            'input_to_statechange', {'Chi', cfix_statename, 'Lhi', 'current_state+1', 'Rhi', 'current_state+1'});
        
        %TODO: how to say stop playing sounds? say you want to stop playing
        %danger and start playing warning for the next state:
        
        %         sma = AddGetOutSidepokeState(sma, [warning_sound, danger_sound], [warning_sound_duration, max_danger_sound_duration], stayout_time);
        
        
        sma = add_state(sma, 'name', 'get_out_spoke', ...
            'self_timer', min_time, ...
            'input_to_statechange', {'Lin', 'current_state+1', 'Rin', 'current_state+1', 'Tup', 'current_state+1'});
        
        sma = add_state(sma, ...
            'self_timer', warning_sound_duration, ...
            'output_actions', {'SoundOut', warning_sound}, ...
            'input_to_statechange', {'Lout', 'current_state+1', 'Rout', 'current_state+1', ...
            'Cin', 'double_poke', 'Rin', 'double_poke', 'Lin', 'double_poke', ...
            'Tup', 'current_state+2', });
        
        sma = add_state(sma, ...
            'self_timer', stayout_time, ...
            'input_to_statechange', {'Tup', 'begin_trial', 'Lin', 'current_state-1', 'Rin', 'current_state-1'});
        
        sma = add_state(sma, ...
            'output_actions', {'SoundOut', danger_sound}, ...
            'input_to_statechange', {'Lout', 'current_state+1', 'Rout', 'current_state+1', ...
            'Cin', 'double_poke', 'Rin', 'double_poke', 'Lin', 'double_poke'});
        
        sma = add_state(sma, ...
            'self_timer', stayout_time, ...
            'input_to_statechange', {'Tup', 'begin_trial', 'Lin', 'current_state-1', 'Rin', 'current_state-1'});
        
        
        sma = add_state(sma, 'name', cfix_statename, ...
            'output_actions', {'SchedWaveTrig', 'cfix_timer', 'DOut', cfix_lights}, ...
            'input_to_statechange', {'cfix_timer_In', 'delay', 'Clo', 'current_state+1', ...
                'Lhi', 'double_poke', 'Rhi', 'double_poke'});
        
%         sma = AddCfixViolationState(sma, cviolation_time, {'DOut', left1led+right1led}, 'cfix_timer');
        sma = add_state(sma, ...
            'self_timer', cviolation_time, ...
            'output_actions', {'DOut', cfix_lights}, ...
            'input_to_statechange', {'cfix_timer_In', 'delay', 'Chi', cfix_statename, 'Tup', 'cbreak_clr_snds'});

        sma = add_multi_sounds_state(sma, -1*snd_list,'state_name','cbreak_clr_snds','return_state','cbreak');        
        
        sma = add_state(sma, 'name', 'cbreak', ...
            'self_timer', cbreak_penalty_time, ...
            'output_actions', {'SoundOut', danger_sound, 'SchedWaveTrig', '-cfix_timer'}, ...
            'input_to_statechange', {'Tup', 'begin_trial'});
        
        
%         sma = add_state(sma, 'name', 'delay', ...
%             'self_timer', delay_time, ...
%             'input_to_statechange', {'Tup', ['play_que_', que_side]});
        
        sma = add_state(sma, 'name', 'delay', ...
            'input_to_statechange', {'Clo', ['play_que_', que_side]});

        sma = add_state(sma, 'name', ['play_que_', que_side], ...
            'output_actions', {'SoundOut', que_sound}, ...
            'input_to_statechange', {[upper(wrong_side), 'hi'], 'wrong_spoke', ...
                                     [upper(target), 'hi'], 'correct_spoke'} ...
                                     );
        
        sma = add_state(sma, 'name', 'correct_spoke', ...
            'self_timer', min_time, ...
            'input_to_statechange', {'Tup', ['deliver_water_', target], ...
                                     ... %[upper(wrong_side), 'hi'], 'double_poke', ...
                                     ... %'Chi', 'double_poke'
                                     });
                                 
        sma = add_state(sma, 'name', ['deliver_water_', target], ...
            'self_timer', water_delivery_time, ...
            'output_actions', {'DOut', target1water}, ...
            'input_to_statechange', {'Tup', ['drinking_time_', target]});
        
        sma = add_state(sma, 'name', ['drinking_time_', target], ...
            'self_timer', drinking_time, ...
            'input_to_statechange', {'Tup', 'end_trial'});
        
        if(TrialSection(obj, 'forgiving') == 1)
            disp('**************** forgiveness is on *************');
            sma = add_state(sma, 'name', 'wrong_spoke', ...
                'self_timer', penalty_time, ...
                'output_actions', {'SoundOut', danger_sound}, ...
                'input_to_statechange', {'Tup', 'end_trial', [upper(target), 'hi'], 'current_state+1'});
            
            sma = add_multi_sounds_state(sma, -1*snd_list,'return_state', 'second_chance');

            sma = add_state(sma, 'name', 'second_chance', ...
                'output_actions', {'SchedWaveTrig', 'forgiveness_timer', 'SoundOut', que_sound}, ...
                'input_to_statechange', {'forgiveness_timer_In', ['forgiving_', target], ...
                    ...%[upper(target), 'lo'], 'current_state+1' % Ran this line until March 22nd (inclusively)
                    });
            
            sma = add_state(sma, ...
                'self_timer', cviolation_time, ...
                'input_to_statechange', {'forgiveness_timer_In', ['forgiving_', target], ...
                    [upper(target), 'hi'], 'current_state-1', 'Tup', 'lost_your_chance'});
                
            sma = add_state(sma, 'name', 'lost_your_chance', ...
                'output_actions', {'SchedWaveTrig', '-forgiveness_timer'}, ...
                'self_timer', min_time, ...
                'input_to_statechange', {'Tup', 'wrong_spoke'});
            
                
            sma = add_state(sma, 'name', ['forgiving_', target], ...
                'self_timer', water_delivery_time, ... %TODO: not good if debiasing with L/R water ratio.
                'output_actions', {'DOut', target1water}, ...
                'input_to_statechange', {'Tup', 'current_state+1'});
            
            sma = add_state(sma, 'name', 'forgiveness_drink_time', ...
                'self_timer', drinking_time, ...
                'input_to_statechange', {'Tup', 'end_trial'});
                
        else
            sma = add_state(sma, 'name', 'wrong_spoke', ...
                'self_timer', penalty_time, ...
                'output_actions', {'SoundOut', danger_sound}, ...
                'input_to_statechange', {'Tup', 'end_trial'});
        end
        
        %TODO: Why do you need to clear all sounds?
%         sma = add_multi_sounds_state(sma, -1*snd_list,'state_name','double_poke','return_state', 'double_poke_post');

        sma = add_state(sma, 'name', 'double_poke', 'self_timer', max_danger_sound_duration, ...
            'output_actions', {'SoundOut', danger_sound}, ...
            'input_to_statechange', {'Lout', 'end_trial', 'Rout', 'end_trial', 'Cout', 'end_trial', 'Tup', 'end_trial'});
        
%         sma = add_multi_sounds_state(sma, -1*snd_list,'state_name','penalty_wait','return_state','penalty_wait_post');
%         
%         sma = add_state(sma, 'name', 'penalty_wait_post', ...
%             'self_timer', penalty_wait_time, ...
%             'input_to_statechange', {'Tup', 'end_trial'});
%         
        sma = add_multi_sounds_state(sma, -1*snd_list,'state_name','end_trial','return_state','check_next_trial_ready');
        
        prepare_next_trial_states = {'correct_spoke', 'wrong_spoke', 'double_poke'};
        
        dispatcher('send_assembler', sma, prepare_next_trial_states);
        
        
    
    case 'state_colors'
        %% case state_colors
        varargout{1} = struct( ...
            'wait_for_cpoke',           [0 0 0]/255, ...
            'cfix_pro',                 [230 170 80]/255, ...
            'cfix_anti',                [255 255 0]/255, ...
            'delay',                    [0 0 0], ...
            'play_que_l',               [150 150 30]/255, ...
            'play_que_r',               [150 30 150]/255, ...
            'deliver_water_l',          [70 230 70]/255, ...
            'deliver_water_r',          [70 70 230]/255, ...
            'drinking_time_l',          [0 255 0]/255, ...
            'drinking_time_r',          [0 0 255]/255, ...
            'forgiving_l',              [150 250 150]/255, ...
            'forgiving_r',              [150 150 250]/255, ...
            'forgiveness_drink_time',   [.5 1 .9], ...
            'double_poke',              [190 0 0]/255, ...
            'wrong_spoke',              [255 0 0]/255, ...
            'second_chance',            [240 160 160]/255, ...
            'cbreak',                   [255 0 0]/255, ...
            'get_out_spoke',            [255 120 0]/255);
        
    case 'poke_colors'
        %% case poke_colors;
        varargout{1} = struct( ...
            'L',                  [1 1 1 ],    ...
            'C',                  [1 1 1],       ...
            'R',                  [1 1 1]);
        
    otherwise
        disp('SMASection ERROR: unknown case');
        
end

end

function [sma] = AddGetOutSidepokeState(sma, sounds, durations, stayout_time)

assert(all(size(sounds) == size(durations)));

for i = 1:numel(sounds)
    home = sprintf('current_state+%d', (numel(sounds)-i)*2+1);
    
    if(i == numel(sounds))
        input_to_statechange = {'Lout', 'current_state+1', 'Rout', 'current_state+1', 'Cin', 'double_poke'};
    else
        input_to_statechange = {'Lout', 'current_state+1', 'Rout', 'current_state+1', 'Cin', 'double_poke', ...
            'Tup', 'current_state+2', };
    end
    
    sma = add_state(sma, ...
        'self_timer', durations(i), ...
        'output_actions', {'SoundOut', sounds(i)}, ...
        'input_to_statechange', input_to_statechange);
    
    sma = add_state(sma, ...
        'self_timer', stayout_time, ...
        'input_to_statechange', {'Tup', home, 'Lin', 'current_state-1', 'Rin', 'current_state-1'});
end

sma = add_multi_sounds_state(sma, -1*sounds,'return_state', sprintf('current_state-%d', numel(sounds)*2+1));

end

function [sma] = AddCfixViolationState(sma, cviolation_time, output_actions, timer)

sma = add_state(sma, ...
    'self_timer', cviolation_time, ...
    'output_actions', output_actions, ...
    'input_to_statechange', {[timer,'_In'], 'current_state+1', 'Chi', 'current_state-1', 'Tup', 'cbreak_clr_snds'});

end
