%
% PARAMETERS:
% -----------
%
% obj      Default object argument.
%
% action   One of:
%
%            'prepare_next_trial'   Returns a @StateMachineAssembler
%                        object, ready to be sent to dispatcher, and a cell
%                        of strings containing the 'prepare_next_trial'
%                        states.
%
%            'get_state_colors'     Returns a structure where each
%                        fieldname is a state name, and each field content
%                        is a color for that state.
%
%
% RETURNS:
% --------
%
% [sma, prepstates]      When action == 'prepare_next_trial', sma is a
%                        @StateMachineAssembler object, ready to be sent to
%                        dispatcher, and prepstates is a a cell
%                        of strings containing the 'prepare_next_trial'
%                        states.
%
% state_colors           When action == 'get_state_colors', state_colors is
%                        a structure where each fieldname is a state name,
%                        and each field content is a color for that state.
%
%
%
% REQUIRES READ-ONLY SOLOPARAMHANDLES:
% ------------------------------------
%
% PokeMeasureTime, RewardTime, PostCSTime, WaterDelivery, WaterBlock
%



function [varargout] = SMASection(obj, action)
   
GetSoloFunctionArgs(obj);

switch action
    
    case 'init'
       
        CP_duration = init_CP_duration;
        SoundManagerSection(obj, 'init');
        %SoundSection(obj, 'init', x, y);
        srate=SoundManagerSection(obj,'get_sample_rate');
        freq1=5;
        dur1=1.5*1000;
        Fs=SoundManagerSection(obj, 'get_sample_rate' ); sound_dur=0.2; sound_vol=0.005;
        Vol=1;
        tw=Vol*(MakeBupperSwoop(srate,0, freq1 , freq1 , dur1/2 , dur1/2,0,0.1));
        SoundManagerSection(obj, 'declare_new_sound', 'LRewardSound', [tw ; zeros(1, length(tw))])
        SoundManagerSection(obj, 'declare_new_sound', 'RRewardSound', [zeros(1, length(tw));tw])
        %% Christine is declaring all of these as new sounds during debugging
        SoundManagerSection(obj, 'declare_new_sound', 'ViolationSound');
        SoundInterface(obj,'set','ViolationSound','Style','WhiteNoiseRamp','Vol',0.01,'Dur1',violation_iti); 
        %SoundManagerSection(obj, 'set_sound', 'ViolationSound', sound_vol*chirp(linspace(0,sound_dur,round(sound_dur*Fs)),8000,1,400) );
        %viol_sound_id     = SoundManagerSection(obj, 'get_sound_id', 'ViolationSound');
        %SoundInterface(obj,'set','ViolationSound','Vol',0.01,'Freq',9000,'Dur1',0.5); 
        SoundManagerSection(obj, 'declare_new_sound', 'ErrorSound');
        SoundManagerSection(obj, 'declare_new_sound', 'TimeoutSound');
        SoundManagerSection(obj, 'declare_new_sound', 'GoSound');
        SoundManagerSection(obj, 'declare_new_sound', 'RewardSound');
        SoundManagerSection(obj, 'declare_new_sound', 'SOneSound');
        SoundManagerSection(obj, 'declare_new_sound', 'STwoSound');
        SoundManagerSection(obj, 'declare_new_sound', 'NICSound');
        SoundManagerSection(obj, 'declare_new_sound', 'PASound');
        SoundManagerSection(obj, 'declare_new_sound', 'StimAUD1');
        SoundManagerSection(obj, 'declare_new_sound', 'StimAUD2');
        
        %% CHRISTINE ADDED THE NIC SOUND HERE
        %SoundInterface(obj, 'set','NICSound','Style','AMTone', 'Vol', 0.003, 'Dur1', init_CP_duration);
        SoundInterface(obj, 'set','GoSound','Style','Tone', 'Vol', 0.01,'Freq1', 2000, 'Dur1', 0.2);

        %SoundInterface(obj, 'set','NICSound','Dur1', init_CP_duration);
        Fs=SoundManagerSection(obj, 'get_sample_rate' ); sound_dur=0.2; sound_vol=0.005;
        %SoundManagerSection(obj, 'declare_new_sound', 
        
    case 'prepare_next_trial',
        %% Setup water
		min_time= 2.5E-4;  % This is less than the minumum time allowed for a state transition.
		
        %% output lines
        left1led     = bSettings('get', 'DIOLINES', 'left1led');
        center1led   = bSettings('get', 'DIOLINES', 'center1led');
        right1led    = bSettings('get', 'DIOLINES', 'right1led');
        left1water   = bSettings('get', 'DIOLINES', 'left1water');
        right1water  = bSettings('get', 'DIOLINES', 'right1water');
        
        %% Christine added extra output channels
        CW           = bSettings('get', 'DIOLINES', 'A5');              %Ch4  5V
        B12          = bSettings('get', 'DIOLINES', 'B12');             %Ch5 12V
        CCW          = bSettings('get', 'DIOLINES', 'B5');              %Ch5  5V
        
		%% Setup sounds
        %[x, y] = SoundSection(obj, 'init', x, y);
        %SoundManagerSection(obj, 'send_not_yet_uploaded_sounds', x, y);
		sone_sound_id     = SoundManagerSection(obj, 'get_sound_id', 'SOneSound');
		stwo_sound_id     = SoundManagerSection(obj, 'get_sound_id', 'STwoSound');
		go_sound_id       = SoundManagerSection(obj, 'get_sound_id', 'GoSound');
		go_cue_duration   = SoundManagerSection(obj, 'get_sound_duration', 'GoSound');
		RLreward_sound_id = SoundManagerSection(obj, 'get_sound_id', 'RewardSound');
		err_sound_id      = SoundManagerSection(obj, 'get_sound_id', 'ErrorSound');
		viol_sound_id     = SoundManagerSection(obj, 'get_sound_id', 'ViolationSound');
		viol_snd_duration = SoundManagerSection(obj, 'get_sound_duration', 'ViolationSound');
		to_sound_id       = SoundManagerSection(obj, 'get_sound_id', 'TimeoutSound');
		timeout_duration  = SoundManagerSection(obj, 'get_sound_duration', 'TimeoutSound');
		Lreward_sound_id  = SoundManagerSection(obj, 'get_sound_id', 'LRewardSound');
		Rreward_sound_id  = SoundManagerSection(obj, 'get_sound_id', 'RRewardSound');
                
        %% THIS ISN'T WORKING
        %SoundInterface(obj, 'set','NICSound','Dur1', CP_duration);
        %SoundInterface(obj, 'set','NICSound','Dur1', 0);
        %InPokeSound=SoundManagerSection(obj, 'get_sound_id', 'NICSound');
        SoundManagerSection(obj, 'send_not_yet_uploaded_sounds');
        
        %InPokeSound_id = SoundManagerSection(obj, 'get_sound_id', 'NICSound');
		
		
        A1_sound_id  = SoundManagerSection(obj, 'get_sound_id', 'StimAUD1');
        A2_sound_id  = SoundManagerSection(obj, 'get_sound_id', 'StimAUD2');

		%% Declare variables
		% These will get moved to other functions as SoloParamHandles.
				
        WaterAmount=maxasymp + (minasymp./(1+(n_done_trials/inflp).^slp).^assym);
        WaterValvesSection(obj, 'set_water_amounts', WaterAmount, WaterAmount);
        [LeftWValveTime RightWValveTime] = WaterValvesSection(obj, 'get_water_times');
		[LeftWMult RightWMult] = SideSection(obj, 'get_water_mult');
		LeftWValveTime=LeftWValveTime*LeftWMult;
		RightWValveTime=RightWValveTime*RightWMult;
		
        side = SideSection(obj, 'get_current_side');
        %stim = StimulusSection(obj, 'get_stimulus', side);
        if side == 'l'
			HitEvent = 'Lin';      ErrorEvent = 'Rin'; 
			HitState = 'lefthit';  SideLight  = left1led; 
            SecondHitState = 'secondlefthit';
            HitState_slot = 'lefthit';  
            SecondHitState_slot = 'secondlefthit_slot';
			
        else
            HitEvent = 'Rin';      ErrorEvent = 'Lin';
            HitState = 'righthit'; SideLight  = right1led;
            SecondHitState = 'secondrighthit';
            HitState_slot = 'righthit';  
            SecondHitState_slot = 'secondrighthit_slot';
        end;
        
        if strcmp(reward_type, 'Always')
            LEDOn=1;
            AnyReward=1;
            wait_for_second_hit=30000;
            error_iti=0;
        elseif strcmp(reward_type, 'NoReward')
            if n_done_trials < value(warmuptrials)
                LEDOn = 1;
                AnyReward = 1;
                wait_for_second_hit=30000;
            elseif n_done_trials >= value(warmuptrials)
                LEDOn=0;
                AnyReward=0;
                wait_for_second_hit=error_iti;
            end
        else
            if n_done_trials < value(warmuptrials)
                LEDOn = 1;
                AnyReward = 1;
                wait_for_second_hit=30000;
            elseif n_done_trials >= value(warmuptrials)
                LEDOn = 0;
                AnyReward=1;
                wait_for_second_hit=30000;
                error_iti=0;
            end  
        end;
     
        [LtValve, RtValve] = WaterValvesSection(obj, 'get_water_times');

    
    PASound_id = SoundManagerSection(obj,  'get_sound_id',       'PASound');
    PASound_dur = SoundManagerSection(obj, 'get_sound_duration', 'PASound');


    sma = StateMachineAssembler('full_trial_structure', 'use_happenings', 1,'n_input_lines', 6); 
    
    %% ----------------Stage Commands--------------------------------------
        sma = add_scheduled_wave(sma, 'name', 'forward', 'preamble', 0, 'sustain', .001,'DOut', CW, 'loop', -1 );
        %sma = add_scheduled_wave(sma, 'name', 'backward','preamble', 0, 'sustain', .001,'DOut', CCW, 'loop', 1);
        sma = add_scheduled_wave(sma, 'name', 'backward', 'preamble', 0, 'sustain', .001,'DOut', CCW, 'loop', value(NosPos));
        sma = add_scheduled_wave(sma, 'name', 'step', 'preamble', 0, 'sustain', .01,'DOut', CCW, 'loop', value(StepSize));
        %sma = add_scheduled_wave(sma, 'name', 'step', 'preamble', 0, 'sustain', value(StepSize)*.001,'DOut', CCW, 'loop', value(StepSize)*.001);
        
    %% ----------------Piston Commands-------------------------------------- 
       if value(CP_duration) > .6;
           early = [0:600];
           early = early.*(value(thispressure)/600);
           late = (value(CP_duration)-0.6)*1000;
           latewaveform=ones(1,late)*value(thispressure);
           waveform = [early, latewaveform];%1000 = 1sec on this rig
       else
           waveform = ones(1,value(CP_duration)*1000)*value(thispressure);
       end
       
       sma = add_scheduled_wave(sma, 'name', 'pistons','ao_line', 2, 'analog_waveform', waveform, 'loop', 0);

       
       %% STATES
        
       %% Initialization state for moving the center poke stage
       if n_done_trials==0
           sma = add_state(sma, 'name', 'MoveForward', ...
               'output_actions', {'SchedWaveTrig', '+forward'}, ...
               'input_to_statechange', {'Ahi', 'Stop'});
           
           sma = add_state(sma, 'name', 'Stop', 'self_timer', 0.001, ...
               'output_actions', {'SchedWaveTrig', '-forward'}, ...
               'input_to_statechange', {'Tup', 'MoveBack'});
           
           sma = add_state(sma, 'name', 'MoveBack', 'self_timer', value(NosPos)*0.002, ...
               'output_actions', {'SchedWaveTrig','+backward'}, ...
               'input_to_statechange', {'Tup', 'wait_for_cpoke'});
       end  %End of move stage, beginning of behavioral trial
        
        %% Christine added this...NIC sound.
        %sma = add_scheduled_wave(sma, 'name', 'center_poke', 'preamble',  0, 'sustain', CP_duration, 'sound_trig', value(InPokeSound));
        sma = add_scheduled_wave(sma, 'name', 'center_poke', 'preamble',  0, 'sustain', CP_duration);
        sma = add_scheduled_wave(sma, 'name', 'go', 'preamble', CP_duration, 'sustain', 0.2, 'sound_trig', go_sound_id);
        sma = add_scheduled_wave(sma, 'name', 'settling_period', 'preamble', SettlingIn_time);
     
       
		% ---BEGIN: for training stage 0 only---
		if side=='l',
			sma = add_scheduled_wave(sma, 'name', 'reward_delivery', 'preamble', reward_delay, ...
				'sustain', LeftWValveTime, 'DOut', left1water);
            reward_sound_id=Lreward_sound_id;
		else
			sma = add_scheduled_wave(sma, 'name', 'reward_delivery', 'preamble', reward_delay, ...
				'sustain', RightWValveTime, 'DOut', right1water);
            reward_sound_id=Rreward_sound_id;
		end;
		% ---END: for training stage 0 only---

        
        if n_done_trials < value(warmuptrials)
            
            sma = add_scheduled_wave(sma, 'name', 'stimA1', 'preamble', 0,...
                'sustain', 0);
            
            sma = add_scheduled_wave(sma, 'name', 'stimA2', 'preamble', CP_duration, ...
                'sustain', 0);
        elseif n_done_trials >= value(warmuptrials)
            
            sma = add_scheduled_wave(sma, 'name', 'stimA1', 'preamble', PreStim_time,...
                'sustain', A1_time, 'sound_trig', A1_sound_id);
            
            sma = add_scheduled_wave(sma, 'name', 'stimA2', 'preamble', PreStim_time+A1_time+Del_time, ...
                'sustain', A2_time,'sound_trig', A2_sound_id);
        end
		
		
		
		switch value(training_stage)
			
			case 0  %% growing nospos/delay
                
				sma = add_state(sma,'name','wait_for_cpoke','self_timer',CenterLed_duration, ...
                    'output_actions', {'DOut', center1led},...
					'input_to_statechange', {'Chi', 'cp','Dhi','cpslotonly','Tup','wait_for_cpoke'});
				
                if stimuli_on ==0 || n_done_trials <1
                % center poke starts: trigger center_poke scheduled wave,
				% and when that ends go to side_led_on
				sma = add_state(sma,'name','cp','self_timer', SettlingIn_time, ...
					'output_actions', {'SchedWaveTrig', 'center_poke + settling_period + go'}, ...
					'input_to_statechange', {'Tup', 'cp_legal_cbreak_period', ...
					    'Clo','legalbreak', ...
					    'center_poke_Out', 'wait_for_collecting_reward', ...
						'Rin',  'violation_state', ...
						'Rout', 'violation_state', ...
						'Lin', 'violation_state', ...
						'Lout', 'violation_state'});
                    
                    sma = add_state(sma,'name','cpslotonly','self_timer', SettlingIn_time, ...
					'output_actions', {'SchedWaveTrig', 'center_poke + settling_period + go'}, ...
					'input_to_statechange', {'Tup', 'cp_legal_cbreak_period_slot', ...
					    'Dlo','legalbreak_slot', ...
					    'center_poke_Out', 'wait_for_collecting_reward', ...
						'Rin',  'violation_state', ...
						'Rout', 'violation_state', ...
						'Lin', 'violation_state', ...
						'Lout', 'violation_state'});
                else
                    
				% center poke starts: trigger center_poke scheduled wave,
				% and when that ends go to side_led_on
				sma = add_state(sma,'name','cp','self_timer', SettlingIn_time+0.00001, ...
					'output_actions', {'SchedWaveTrig', 'center_poke + settling_period + go'}, ...
					'input_to_statechange', {'Tup', 'cp_legal_cbreak_period', ...
					    'Clo','legalbreak', ...
					    'center_poke_Out', 'wait_for_collecting_reward', ...
						'Rin',  'violation_state', ...
						'Rout', 'violation_state', ...
						'Lin', 'violation_state', ...
						'Lout', 'violation_state'});
                    
                    sma = add_state(sma,'name','cpslotonly','self_timer', SettlingIn_time+0.00001, ...
					'output_actions', {'SchedWaveTrig', 'center_poke + settling_period + go'}, ...
					'input_to_statechange', {'Tup', 'cp_legal_cbreak_period_slot', ...
					    'Dlo','legalbreak_slot', ...
					    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
						'Rin',  'violation_state', ...
						'Rout', 'violation_state', ...
						'Lin', 'violation_state', ...
						'Lout', 'violation_state'});
                    
                    
                end
               
              
                % nose is out and we're in "SettlingIn_time":
                % if settling_legal_cbreak time elapses, go to violation state,
                % if nose is put back in, go to copy of cp start
                % when SettlingIn_time elapses (settling_period_In) "legal cbreaks" changes to usueal legal_cbreaks
                sma = add_state(sma, 'name', 'legalbreak','self_timer', settling_legal_cbreak+0.00001, ...
                    'output_actions', {'DOut', center1led},...
                    'input_to_statechange', {'Tup', 'violation_state', ...
                    'Chi', 'cp_settlingin', ...
                    'settling_period_In', 'cp_legal_cbreak_period', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                sma = add_state(sma, 'name', 'legalbreak_slot','self_timer', settling_legal_cbreak+0.00001, ...
                    'output_actions', {'DOut', center1led},...
                    'input_to_statechange', {'Tup', 'violation_state', ...
                    'Dhi', 'cpslot_settlingin', ...
                    'settling_period_In', 'cp_legal_cbreak_period_slot', ...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                % center poke:
				% A copy of two states above, but without triggering the
				% start of the center_poke scheduled wave. 
                sma = add_state(sma, 'name', 'cp_settlingin','self_timer', 10000, ...
                    'input_to_statechange', {'Clo', 'legalbreak', ...
                    'settling_period_In','cp_legal_cbreak_period', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                
                sma = add_state(sma, 'name', 'cpslot_settlingin','self_timer', 10000, ...
                    'input_to_statechange', {'Dlo', 'legalbreak_slot', ...
                    'settling_period_In','cp_legal_cbreak_period_slot', ...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                % SettlingIn_time elapsed and from now on cbreaks are treated given legal_cbreaks    
                sma = add_state(sma,'name','cp_legal_cbreak_period', 'self_timer', 10000, ...
                    'input_to_statechange', {'Cout', 'postsettle_legalbreak', ...
                    'Clo', 'postsettle_legalbreak', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                 
                sma = add_state(sma,'name','cp_legal_cbreak_period_slot', 'self_timer', 10000, ...
                    'input_to_statechange', {'Dlo', 'postsettle_legalbreak_slot',...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                
                % nose is out and we're still in legal_cbreak:
				% if legal_cbreak time elapses, go to violation_state, 
				% if nose is put back in, go to copy of cp start
                sma = add_state(sma, 'name', 'postsettle_legalbreak', 'self_timer', legal_cbreak+0.00001, ...
                    'output_actions', {'DOut', center1led},...
                    'input_to_statechange', {'Tup', 'violation_state', ...
                    'Chi', 'cp_postsettle', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                
                sma = add_state(sma, 'name', 'postsettle_legalbreak_slot', 'self_timer', legal_cbreak+0.00001, ...
                    'output_actions', {'DOut', center1led},...
                    'input_to_statechange', {'Tup', 'violation_state', ...
                    'Dhi', 'cp_postsettle_slot', ...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                    
				
				% center poke:
				% A copy of two states above, but without triggering the
				% start of the center_poke scheduled wave. 
                sma = add_state(sma, 'name', 'cp_postsettle', 'self_timer', 10000, ...
                    'input_to_statechange', {'Clo', 'postsettle_legalbreak', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                sma = add_state(sma, 'name', 'cp_postsettle_slot', 'self_timer', 10000, ...
                    'input_to_statechange', {'Dlo', 'postsettle_legalbreak_slot', ...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
				
                sma = add_state(sma, 'name', 'wait_for_collecting_reward', 'self_timer', 30000, ...
                    'output_actions', {'DOut', LEDOn*SideLight}, ...
                    'input_to_statechange',{HitEvent, HitState, ErrorEvent, 'second_hit_state',...
                    'Tup', 'nomove'});
                
                sma = add_state(sma, 'name', 'wait_for_collecting_reward_slot', 'self_timer', 30000, ...
                    'output_actions', {'DOut', LEDOn*SideLight}, ...
                    'input_to_statechange',{HitEvent, HitState_slot, ErrorEvent, 'second_hit_state_slot',...
                    'Tup', 'nomove'});
                
%                 sma = add_state(sma, 'name', 'nomove', 'self_timer', 0.001, ...
%                     'input_to_statechange', {'Tup', 'check_next_trial_ready'});
                
                % The two states that make a LeftHit:
                % without microswitches
				sma = add_state(sma,'name', 'lefthit','self_timer', reward_delay, ...
					'output_actions', {'DOut', SideLight', 'SoundOut', Lreward_sound_id}, ...					
					'input_to_statechange', {'Tup', 'current_state+1'});				
				sma = add_state(sma, 'self_timer', LeftWValveTime, ...
                    'output_actions', {'DOut', SideLight+left1water,},...
                    'input_to_statechange',{'Tup','hit_state'});
                
                %with microswitches
                sma = add_state(sma,'name', 'lefthit_slot','self_timer', reward_delay, ...
                    'output_actions', {'DOut', SideLight', 'SoundOut', Lreward_sound_id}, ...
                    'input_to_statechange', {'Tup', 'current_state+1'});
                sma = add_state(sma, 'self_timer', LeftWValveTime, ...
                    'output_actions', {'DOut', SideLight+left1water,},...
                    'input_to_statechange',{'Tup','hit_state_slot'});

				% The two states that make a RightHit:
				sma = add_state(sma,'name', 'righthit_slot','self_timer', reward_delay, ...
					'output_actions', {'DOut', SideLight', 'SoundOut', Rreward_sound_id}, ...					
					'input_to_statechange', {'Tup', 'current_state+1'});				
				sma = add_state(sma, 'self_timer', RightWValveTime, ...
					'output_actions', {'DOut', SideLight+right1water,},...
					'input_to_statechange',{'Tup','hit_state_slot'});

                sma = add_state(sma,'name','second_hit_state','self_timer', wait_for_second_hit,...
                    'output_actions',{'DOut', LEDOn*SideLight},...
                    'input_to_statechange',{HitEvent, SecondHitState,'Tup','check_next_trial_ready'});
                
                sma = add_state(sma,'name','second_hit_state_slot','self_timer', wait_for_second_hit,...
                    'output_actions',{'DOut', LEDOn*SideLight},...
                    'input_to_statechange',{HitEvent, SecondHitState_slot,'Tup','check_next_trial_ready'});
				

                % The two states that make a SecondLeftHit:
                % without microswitches
				sma = add_state(sma,'name', 'secondlefthit','self_timer', secondhit_delay, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});	
                sma = add_state(sma, 'self_timer', reward_delay, ...
					'output_actions', {'DOut', AnyReward*SideLight', 'SoundOut', AnyReward*Lreward_sound_id}, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});
				sma = add_state(sma, 'self_timer', LeftWValveTime, ...
					'output_actions', {'DOut', AnyReward*(SideLight+left1water)},...
					'input_to_statechange',{'Tup','hit_state'});

                % with microswitches
                sma = add_state(sma,'name', 'secondlefthit_slot','self_timer', secondhit_delay, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});	
                sma = add_state(sma, 'self_timer', reward_delay, ...
					'output_actions', {'DOut', AnyReward*SideLight', 'SoundOut', AnyReward*Lreward_sound_id}, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});
				sma = add_state(sma, 'self_timer', LeftWValveTime, ...
					'output_actions', {'DOut', AnyReward*(SideLight+left1water)},...
					'input_to_statechange',{'Tup','hit_state_slot'});
                
				% The two states that make a SecondRightHit:
                % without microswitches
				sma = add_state(sma,'name', 'secondrighthit','self_timer', secondhit_delay, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});	
                sma = add_state(sma, 'self_timer', reward_delay, ...
					'output_actions', {'DOut', AnyReward*SideLight', 'SoundOut', AnyReward*Rreward_sound_id}, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});
				sma = add_state(sma, 'self_timer', RightWValveTime, ...
					'output_actions', {'DOut', AnyReward*(SideLight+right1water)},...
					'input_to_statechange',{'Tup','hit_state'});
                
                %with microswitches
                sma = add_state(sma,'name', 'secondrighthit_slot','self_timer', secondhit_delay, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});	
                sma = add_state(sma, 'self_timer', reward_delay, ...
					'output_actions', {'DOut', AnyReward*SideLight', 'SoundOut', AnyReward*Rreward_sound_id}, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});
				sma = add_state(sma, 'self_timer', RightWValveTime, ...
					'output_actions', {'DOut', AnyReward*(SideLight+right1water)},...
					'input_to_statechange',{'Tup','hit_state_slot'});
                
                % and a common hit_state that we flick through
                sma = add_state(sma, 'name', 'hit_state', 'self_timer', 0.0001, ...
                    'input_to_statechange', {'Tup', 'movestage'});
                
                sma = add_state(sma, 'name', 'hit_state_slot', 'self_timer', 0.0001, ...
                    'input_to_statechange', {'Tup', 'nomove'});
% 				sma = add_state(sma, 'name', 'sideled_on', 'self_timer', SideLed_duration, ...
% 					'output_actions', {'DOut', SideLight}, ...
% 					'input_to_statechange',{'Tup','wait_for_collecting_reward'});
% 				
% 				sma = add_state(sma, 'name', 'wait_for_collecting_reward', 'self_timer', RewardCollection_duration, ...
% 					'output_actions', {'DOut', SideLight}, ...
% 					'input_to_statechange',{HitEvent,'hit_state','Tup','wait_for_collecting_reward',ErrorEvent,'second_hit_state'});
%                 
%                 sma = add_state(sma, 'name', 'wait_for_collecting_reward_slot', 'self_timer', 30000, ...
%                     'output_actions', {'DOut', LEDOn*SideLight}, ...
%                     'input_to_statechange',{HitEvent, HitState, ErrorEvent, 'second_hit_state_slot',...
%                     'Tup', 'nomove'});
%                 
%                 sma = add_state(sma, 'name', 'nomove', 'self_timer', 0.001, ...
%                     'input_to_statechange', {'Tup', 'check_next_trial_ready'});
%                 
%                 sma = add_state(sma,'name','second_hit_state','self_timer', wait_for_second_hit,...
%                     'output_actions',{'DOut', LEDOn*SideLight},...
%                     'input_to_statechange',{HitEvent, SecondHitState,'Tup','movestage'});
%                 
%                 sma = add_state(sma,'name','second_hit_state_slot','self_timer', wait_for_second_hit,...
%                     'output_actions',{'DOut', LEDOn*SideLight},...
%                     'input_to_statechange',{HitEvent, SecondHitState,'Tup','check_next_trial_ready'});
%                 
%                 sma = add_state(sma, 'name', 'movestage', 'self_timer', value(StepSize)*.002,...
%                     'input_to_statechange', {'Tup', 'check_next_trial_ready'},...
%                     'output_actions', {'SchedWaveTrig', '+step'});
%                 
%                 sma = add_state(sma,'name','hit_state','self_timer',0.01,...
%                     'output_actions', {'DOut', SideLight,'SchedWaveTrig','reward_delivery','SoundOut',reward_sound_id},...
%                     'input_to_statechange',{'Tup','drink_state'});
				
				
			case 1  %%  center led on -> poke in the center -> go cue -> reward light and sound -- waiting time grows slowlly -stimuli can be present
				
				sma = add_state(sma,'name','wait_for_cpoke','self_timer',CenterLed_duration, ...
                    'output_actions', {'DOut', center1led},...
					'input_to_statechange', {'Chi', 'cp','Dhi','cpslotonly','Tup','wait_for_cpoke'});
				
                if stimuli_on ==0 || n_done_trials <1
                % center poke starts: trigger center_poke scheduled wave,
				% and when that ends go to side_led_on
				sma = add_state(sma,'name','cp','self_timer', SettlingIn_time, ...
					'output_actions', {'SchedWaveTrig', 'center_poke + settling_period + go'}, ...
					'input_to_statechange', {'Tup', 'cp_legal_cbreak_period', ...
					    'Clo','legalbreak', ...
					    'center_poke_Out', 'wait_for_collecting_reward', ...
						'Rin',  'violation_state', ...
						'Rout', 'violation_state', ...
						'Lin', 'violation_state', ...
						'Lout', 'violation_state'});
                    
                    sma = add_state(sma,'name','cpslotonly','self_timer', SettlingIn_time, ...
					'output_actions', {'SchedWaveTrig', 'center_poke + settling_period + go'}, ...
					'input_to_statechange', {'Tup', 'cp_legal_cbreak_period', ...
					    'Dlo','legalbreak_slot', ...
					    'center_poke_Out', 'wait_for_collecting_reward', ...
						'Rin',  'violation_state', ...
						'Rout', 'violation_state', ...
						'Lin', 'violation_state', ...
						'Lout', 'violation_state'});
                else
                    
				% center poke starts: trigger center_poke scheduled wave,
				% and when that ends go to side_led_on
				sma = add_state(sma,'name','cp','self_timer', SettlingIn_time+0.00001, ...
					'output_actions', {'SchedWaveTrig', 'center_poke + settling_period +stimA1+stimA2 +pistons + go'}, ...
					'input_to_statechange', {'Tup', 'cp_legal_cbreak_period', ...
					    'Clo','legalbreak', ...
					    'center_poke_Out', 'wait_for_collecting_reward', ...
						'Rin',  'violation_state', ...
						'Rout', 'violation_state', ...
						'Lin', 'violation_state', ...
						'Lout', 'violation_state'});
                    
                    sma = add_state(sma,'name','cpslotonly','self_timer', SettlingIn_time+0.00001, ...
					'output_actions', {'SchedWaveTrig', 'center_poke + settling_period +stimA1+stimA2 +pistons + go'}, ...
					'input_to_statechange', {'Tup', 'cp_legal_cbreak_period_slot', ...
					    'Dlo','legalbreak_slot', ...
					    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
						'Rin',  'violation_state', ...
						'Rout', 'violation_state', ...
						'Lin', 'violation_state', ...
						'Lout', 'violation_state'});
                    
                    
                end
               
              
                % nose is out and we're in "SettlingIn_time":
                % if settling_legal_cbreak time elapses, go to violation state,
                % if nose is put back in, go to copy of cp start
                % when SettlingIn_time elapses (settling_period_In) "legal cbreaks" changes to usueal legal_cbreaks
                sma = add_state(sma, 'name', 'legalbreak','self_timer', settling_legal_cbreak+0.00001, ...
                    'output_actions', {'DOut', center1led},...
                    'input_to_statechange', {'Tup', 'violation_state', ...
                    'Chi', 'cp_settlingin', ...
                    'settling_period_In', 'cp_legal_cbreak_period', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                sma = add_state(sma, 'name', 'legalbreak_slot','self_timer', settling_legal_cbreak+0.00001, ...
                    'output_actions', {'DOut', center1led},...
                    'input_to_statechange', {'Tup', 'violation_state', ...
                    'Dhi', 'cpslot_settlingin', ...
                    'settling_period_In', 'cp_legal_cbreak_period_slot', ...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                % center poke:
				% A copy of two states above, but without triggering the
				% start of the center_poke scheduled wave. 
                sma = add_state(sma, 'name', 'cp_settlingin','self_timer', 10000, ...
                    'input_to_statechange', {'Clo', 'legalbreak', ...
                    'settling_period_In','cp_legal_cbreak_period', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                
                sma = add_state(sma, 'name', 'cpslot_settlingin','self_timer', 10000, ...
                    'input_to_statechange', {'Dlo', 'legalbreak_slot', ...
                    'settling_period_In','cp_legal_cbreak_period_slot', ...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                % SettlingIn_time elapsed and from now on cbreaks are treated given legal_cbreaks    
                sma = add_state(sma,'name','cp_legal_cbreak_period', 'self_timer', 10000, ...
                    'input_to_statechange', {'Cout', 'postsettle_legalbreak', ...
                    'Clo', 'postsettle_legalbreak', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                 
                sma = add_state(sma,'name','cp_legal_cbreak_period_slot', 'self_timer', 10000, ...
                    'input_to_statechange', {'Dlo', 'postsettle_legalbreak_slot',...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                
                % nose is out and we're still in legal_cbreak:
				% if legal_cbreak time elapses, go to violation_state, 
				% if nose is put back in, go to copy of cp start
                sma = add_state(sma, 'name', 'postsettle_legalbreak', 'self_timer', legal_cbreak+0.00001, ...
                    'output_actions', {'DOut', center1led},...
                    'input_to_statechange', {'Tup', 'violation_state', ...
                    'Chi', 'cp_postsettle', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                
                sma = add_state(sma, 'name', 'postsettle_legalbreak_slot', 'self_timer', legal_cbreak+0.00001, ...
                    'output_actions', {'DOut', center1led},...
                    'input_to_statechange', {'Tup', 'violation_state', ...
                    'Dhi', 'cp_postsettle_slot', ...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                    
				
				% center poke:
				% A copy of two states above, but without triggering the
				% start of the center_poke scheduled wave. 
                sma = add_state(sma, 'name', 'cp_postsettle', 'self_timer', 10000, ...
                    'input_to_statechange', {'Clo', 'postsettle_legalbreak', ...
                    'center_poke_Out', 'wait_for_collecting_reward', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
                
                sma = add_state(sma, 'name', 'cp_postsettle_slot', 'self_timer', 10000, ...
                    'input_to_statechange', {'Dlo', 'postsettle_legalbreak_slot', ...
                    'center_poke_Out', 'wait_for_collecting_reward_slot', ...
                    'Rin',  'violation_state', ...
                    'Rout', 'violation_state', ...
                    'Lin', 'violation_state', ...
                    'Lout', 'violation_state'});
				
                sma = add_state(sma, 'name', 'wait_for_collecting_reward', 'self_timer', 30000, ...
                    'output_actions', {'DOut', LEDOn*SideLight}, ...
                    'input_to_statechange',{HitEvent, HitState, ErrorEvent, 'second_hit_state',...
                    'Tup', 'nomove'});
                
                sma = add_state(sma, 'name', 'wait_for_collecting_reward_slot', 'self_timer', 30000, ...
                    'output_actions', {'DOut', LEDOn*SideLight}, ...
                    'input_to_statechange',{HitEvent, HitState_slot, ErrorEvent, 'second_hit_state',...
                    'Tup', 'nomove'});
                
%                 sma = add_state(sma, 'name', 'nomove', 'self_timer', 0.001, ...
%                     'input_to_statechange', {'Tup', 'check_next_trial_ready'});
                
                % The two states that make a LeftHit:
                % without microswitches
				sma = add_state(sma,'name', 'lefthit','self_timer', reward_delay, ...
					'output_actions', {'DOut', SideLight', 'SoundOut', Lreward_sound_id}, ...					
					'input_to_statechange', {'Tup', 'current_state+1'});				
				sma = add_state(sma, 'self_timer', LeftWValveTime, ...
					'output_actions', {'DOut', SideLight+left1water,},...
					'input_to_statechange',{'Tup','hit_state'});
                
                %with microswitches
                sma = add_state(sma,'name', 'lefthit_slot','self_timer', reward_delay, ...
					'output_actions', {'DOut', SideLight', 'SoundOut', Lreward_sound_id}, ...					
					'input_to_statechange', {'Tup', 'current_state+1'});				
				sma = add_state(sma, 'self_timer', LeftWValveTime, ...
					'output_actions', {'DOut', SideLight+left1water,},...
					'input_to_statechange',{'Tup','hit_state_slot'});
                
               

				% The two states that make a RightHit:
                % without microswitches
				sma = add_state(sma,'name', 'righthit','self_timer', reward_delay, ...
					'output_actions', {'DOut', SideLight', 'SoundOut', Rreward_sound_id}, ...					
					'input_to_statechange', {'Tup', 'current_state+1'});				
				sma = add_state(sma, 'self_timer', RightWValveTime, ...
					'output_actions', {'DOut', SideLight+right1water,},...
					'input_to_statechange',{'Tup','hit_state'});
                
                %with microswitches
                sma = add_state(sma,'name', 'righthit_slot','self_timer', reward_delay, ...
					'output_actions', {'DOut', SideLight', 'SoundOut', Rreward_sound_id}, ...					
					'input_to_statechange', {'Tup', 'current_state+1'});				
				sma = add_state(sma, 'self_timer', RightWValveTime, ...
					'output_actions', {'DOut', SideLight+right1water,},...
					'input_to_statechange',{'Tup','hit_state_slot'});
                
                sma = add_state(sma,'name','second_hit_state','self_timer', wait_for_second_hit,...
                    'output_actions',{'DOut', LEDOn*SideLight},...
                    'input_to_statechange',{HitEvent, SecondHitState,'Tup','check_next_trial_ready'});      
				
                 sma = add_state(sma,'name','second_hit_state_slot','self_timer', wait_for_second_hit,...
                    'output_actions',{'DOut', LEDOn*SideLight},...
                    'input_to_statechange',{HitEvent, SecondHitState_slot,'Tup','check_next_trial_ready'}); 
                

                % The two states that make a SecondLeftHit:
                % without microswitches
				sma = add_state(sma,'name', 'secondlefthit','self_timer', secondhit_delay, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});	
                sma = add_state(sma, 'self_timer', reward_delay, ...
					'output_actions', {'DOut', AnyReward*SideLight', 'SoundOut', AnyReward*Lreward_sound_id}, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});
				sma = add_state(sma, 'self_timer', LeftWValveTime, ...
					'output_actions', {'DOut', AnyReward*(SideLight+left1water)},...
					'input_to_statechange',{'Tup','hit_state'});
                
                % with microswitches
                sma = add_state(sma,'name', 'secondlefthit_slot','self_timer', secondhit_delay, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});	
                sma = add_state(sma, 'self_timer', reward_delay, ...
					'output_actions', {'DOut', AnyReward*SideLight', 'SoundOut', AnyReward*Lreward_sound_id}, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});
				sma = add_state(sma, 'self_timer', LeftWValveTime, ...
					'output_actions', {'DOut', AnyReward*(SideLight+left1water)},...
					'input_to_statechange',{'Tup','hit_state_slot'});
                

				% The two states that make a SecondRightHit:
				sma = add_state(sma,'name', 'secondrighthit','self_timer', secondhit_delay, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});	
                sma = add_state(sma, 'self_timer', reward_delay, ...
					'output_actions', {'DOut', AnyReward*SideLight', 'SoundOut', AnyReward*Rreward_sound_id}, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});
				sma = add_state(sma, 'self_timer', RightWValveTime, ...
					'output_actions', {'DOut', AnyReward*(SideLight+right1water)},...
					'input_to_statechange',{'Tup','hit_state'});
                
                % with microswitches
                sma = add_state(sma,'name', 'secondrighthit_slot','self_timer', secondhit_delay, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});	
                sma = add_state(sma, 'self_timer', reward_delay, ...
					'output_actions', {'DOut', AnyReward*SideLight', 'SoundOut', AnyReward*Rreward_sound_id}, ...	
                    'input_to_statechange', {'Tup', 'current_state+1'});
				sma = add_state(sma, 'self_timer', RightWValveTime, ...
					'output_actions', {'DOut', AnyReward*(SideLight+right1water)},...
					'input_to_statechange',{'Tup','hit_state_slot'});
                
				% and a common hit_state that we flick through                
				sma = add_state(sma, 'name', 'hit_state', 'self_timer', 0.0001, ...
					'input_to_statechange', {'Tup', 'movestage'});
                
				sma = add_state(sma, 'name', 'hit_state_slot', 'self_timer', 0.0001, ...
					'input_to_statechange', {'Tup', 'nomove'});
                
				
        end %end of switch for different training_stages
        sma = add_state(sma, 'name', 'movestage', 'self_timer', value(StepSize)*.002,...
            'output_actions',{'SchedWaveTrig', '+step'},'input_to_statechange',...
            {'Tup', 'drink_state'});
        
        sma = add_state(sma, 'name', 'nomove', 'self_timer', 0.001, ...
                     'input_to_statechange', {'Tup', 'drink_state'});
        
        if (AnyReward*drink_time+error_iti)<(value(StepSize)*.001)
            sma = add_state(sma,'name','drink_state','self_timer', .001,...
                'input_to_statechange',{'Tup','check_next_trial_ready'});
        elseif (AnyReward*drink_time+error_iti)>=(value(StepSize)*.001)
            sma = add_state(sma,'name','drink_state','self_timer',(AnyReward*drink_time+error_iti)-...
                (value(StepSize)*.001),'input_to_statechange',{'Tup','check_next_trial_ready'});
        end
		
        if stimuli_on ==0
        sma = add_state(sma,'name','violation_state','self_timer',viol_snd_duration,...
			'output_actions',{'SchedWaveTrig', '-center_poke-pistons-go', ...
			    'SoundOut',viol_sound_id},...
			'input_to_statechange', {'Tup', 'current_state+1'});   
        else
            
		sma = add_state(sma,'name','violation_state','self_timer',viol_snd_duration,...
			'output_actions',{'SchedWaveTrig', '-center_poke-stimA1-stimA2-pistons-go', ...
			    'SoundOut',viol_sound_id},...
			'input_to_statechange', {'Tup', 'current_state+1'});
        end
        
		sma = add_state(sma, 'self_timer', max(0.001, violation_iti-viol_snd_duration), ...
			'input_to_statechange',{'Tup','check_next_trial_ready'});
		
		sma = add_state(sma,'name','timeout_state','self_timer', timeout_duration,...
			'output_actions',{'SoundOut',to_sound_id},...
			'input_to_statechange',{'Tup','check_next_trial_ready'});
		
		
		varargout{2} = {'check_next_trial_ready'};
		
		varargout{1} = sma;
		
		% Not all 'prepare_next_trial_states' are defined in all training
		% stages. So we send to dispatcher only those states that are
		% defined.
		state_names = get_labels(sma); state_names = state_names(:,1);
		prepare_next_trial_states = {'hit_state','hit_state_slot','second_hit_state','second_hit_state_slot',...
            'violation_state','timeout_state', 'nomove', 'movestage'};
        dispatcher('send_assembler', sma, intersect(state_names, prepare_next_trial_states));
		
	case 'get_state_colors',
		varargout{1} = struct( ...
			'wait_for_cpoke',             [0.68  1   0.63], ...
			'cp',                       [0.63  1   0.94], ...
			'cp_legal_cbreak_period',   [0.63  1   0.94]*0.8, ...
			'sideled_on',     [1   0.79  0.63], ...
			'wait_for_collecting_reward', [0.53 0.78 1.00],...
		    'righthit',              [0.3   0.9     0], ...
			'lefthit',               [0     0.9   0.3], ...
		    'hit_state',             [0.77 0.60 0.48], ...
			'second_hit_state',      [0.25 0.45 0.48], ...
			'drink_state',           [0    1    0],    ...
			'error_state',  [1    0.54 0.54], ...
			'violation_state',            [0.31 0.48 0.30], ...
			'timeout_state', 0.8*[0.31 0.48 0.30]);
		%            'go_cue_on',                [0.63  1   0.94]*0.6, ...
		%            'prerw_postcs',      [0.25 0.45 0.48], ...
		%             'lefthit',           [0.53 0.78 1.00], ...
		%             'lefthit_pasound',   [0.53 0.78 1.00]*0.7, ...
		%             'righthit',          [0.52 1.0  0.60], ...
		%             'righthit_pasound',  [0.52 1.0  0.60]*0.7, ...
		%             'warning',           [0.3  0    0],    ...
		%             'danger',            [0.5  0.05 0.05], ...
		%             'hit',               [0    1    0]
		
		
		
		
	case 'reinit',
		currfig = double(gcf);
		
		% Delete all SoloParamHandles who belong to this object and whose
		% fullname starts with the name of this mfile:
		delete_sphandle('owner', ['^@' class(obj) '$'], ...
			'fullname', ['^' mfilename]);
		
		
		% Reinitialise at the original GUI position and figure:
		feval(mfilename, obj, 'init');
		
		% Restore the current figure:
		figure(currfig);
		
	otherwise
		warning('do not know how to do %s',action);
end