function add_rig_to_schedule(rigid)

[id,timeslot] = bdata(['select schedentryid, timeslot from ratinfo.schedule where rig=',...
                       num2str(rigid),' and date="',datestr(now+1,'yyyy-mm-dd'),'"']);
        
if numel(id) == 9
    disp(['All 9 timeslots exist on the schedule for rig ',num2str(rigid)])
    return
end

for i = 1:9
    if sum(timeslot == i) == 0
        disp(['Inserting Rig ',num2str(i),' Session ',num2str(i),' into Schedule for ',datestr(now+1,'yyyy-mm-dd')]);
        bdata(['insert into ratinfo.schedule set ratname=""'             ,... 
                                         ',     timeslot=',num2str(i)    ,...
                                         ', instructions=""'             ,...
                                         ',     comments=""'             ,...
                                         ',          rig=',num2str(rigid),...
                                         ', experimenter=""'             ,...
                                         ',         date="',datestr(now+1,'yyyy-mm-dd'),'"']);
    end
end