function max_state_dur = MaxStateDur(obj) %#ok<INUSD>


max_state_dur = {...
'state_0',                  180;...
'check_next_trial_ready',   180;...
'clean_sound_state',         30;...
'iti',                      120;...
'iti_pun',                  120;...
'wait_for_cpoke1',          Inf;...
'cpoke1_tup_state',          30;...
'cpoke1_tup_prep_trial',     30;...
'cl1_pun',                  120;...
'play_stimulus_sound',       30;...
'cpoke1',                    60;...
'wait_for_center_nose_out', 120;...
'terminate_wfco',           120;...
'punish_wfco',              120;...
'temp_violation',            60;...
'center_2_side_gap',         60;...
'center_2_side_gap_2',       60;...
'c2s_pun',                  120;...
'c2s_pun2',                 120;...
'wait_for_spoke',           Inf;...
'error_state1',             120;...
'error_state',              360;...
'temporary_punishment',     120;...
'violation_state',          120;...
'left_reward',               60;...
'right_reward',              60;...
'hit_state',                 60;...
'drink_state',               60;...
'warning',                   60;...
'danger',                    60;...
'mypun',                    120;...
'soft_drink_state',         120;...
'clean_up_state',            60;...
};